palantir/plottable

- quicktests/overlaying/tests/animations/animate_horizontalBar.js
- quicktests/overlaying/tests/animations/animate_verticalBar.js
- quicktests/overlaying/tests/basic/bars_on_numeric.js
- quicktests/overlaying/tests/basic/grid_plot.js
- quicktests/overlaying/tests/basic/horizontal_clustered_bar.js
- quicktests/overlaying/tests/basic/horizontal_stacked.js
- quicktests/overlaying/tests/basic/legend_reversed.js
- quicktests/overlaying/tests/functional/base_animator.js
- quicktests/overlaying/tests/functional/category_axis_rotated_ticks.js
- quicktests/overlaying/tests/functional/time_tier_config.js
Some quicktests I had hidden under my sleeves.
> Adding new tests to overlay!

- plottable.js
- src/components/plots/abstractStackedPlot.ts
Also using _projectorsReady since that's the main requirement
> [StackedPlot] - Removing HACKHACK

- package.json
- plottable.d.ts
Run
`npm update && npm install`
to update your typescript.
We should regression pass this as this is a library/language upgrade?
> Upgrade to typescript-1.4

- plottable.js
- src/interactions/panZoomInteraction.ts
- test/interactions/interactionTests.ts
- test/tests.js
HACKHACK for now until we get to rewriting `Interaction.PanZoom`.
Close #1388.
> resetZoom() when scale domains change in Interaction.PanZoom.

- plottable.d.ts
- plottable.js
- src/scales/colorScale.ts
- src/utils/utils.ts
- test/scales/scaleTests.ts
- test/tests.js
- test/utils/utilsTests.ts
Same as #1549 
Couldn't check out a numeric-named branch so creating a new PR
> [ColorScale] - Re-enabling color string names as range values

- plottable.d.ts
- plottable.js
- src/scales/colorScale.ts
- src/utils/utils.ts
- test/scales/scaleTests.ts
- test/tests.js
- test/utils/utilsTests.ts
> [Scale.Color] - Correctly parses color strings into rgb

- plottable.js
- src/drawers/rectDrawer.ts
Changing from using setter function to directly setting
> [Drawer] - removing instance methods from constructor

- plottable.js
- src/drawers/arcDrawer.ts
- test/components/plots/piePlotTests.ts
- test/tests.js
> [PiePlot] PiePlot will throw a warning if it has negative values.

- test/components/legendTests.ts
- test/tests.js
> [Tests] Consolidated Legend-related tests

- plottable.d.ts
- plottable.js
- src/components/abstractComponent.ts
- src/components/axes/abstractAxis.ts
- src/components/axes/numericAxis.ts
- src/utils/domUtils.ts
- test/components/numericAxisTests.ts
- test/tests.js
> [Axis] Ensure labels are confined to Axis boundaries, fixes #1501

- plottable.js
- src/components/axes/timeAxis.ts
- test/components/timeAxisTests.ts
- test/tests.js
> [TimeAxis] Fixes inconsitent end tick issues

- package.json
- test/interactions/hoverInteractionTests.ts
Mainly to prepare making our upgrade into using the features in TS1.4
> Upgrading grunt-tslint to 2.0.0

- plottable.d.ts
- plottable.js
- src/components/axes/categoryAxis.ts
- src/components/plots/barPlot.ts
- src/components/plots/gridPlot.ts
- src/scales/ordinalScale.ts
- test/components/categoryAxisTests.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/clusteredBarPlotTests.ts
- test/scales/scaleTests.ts
- test/tests.js
OrdinalScales will now always be in "bands" mode.  Changing the rest of the codebase to reflect the changes.
> [OrdinalScale] - Remove rangeType

- plottable.js
- src/components/axes/abstractAxis.ts
- test/components/baseAxisTests.ts
- test/components/numericAxisTests.ts
- test/tests.js
> [AbstractAxis] More regular behavior for tick visibility

- plottable.d.ts
- plottable.js
- src/scales/ordinalScale.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/clusteredBarPlotTests.ts
- test/interactions/hoverInteractionTests.ts
- test/scales/scaleTests.ts
- test/tests.js
Now the values are in proportion to the bar width.
> [OrdinalScale] - Padding logic completely reworked.

- test/components/numericAxisTests.ts
- test/tests.js
Was failing in FF locally (FF 35.0.1).
> Switch to closeTo in test.

- plottable.js
- src/components/axes/abstractAxis.ts
- src/components/axes/numericAxis.ts
- test/components/numericAxisTests.ts
- test/tests.js
> Fixes #1033 SVG visibility issues with Firefox

- plottable.js
- src/components/axes/timeAxis.ts
- test/components/timeAxisTests.ts
- test/tests.js
> [TimeAxis] Add end-tick-mark class to first and last tick marks

- plottable.d.ts
- plottable.js
- src/drawers/areaDrawer.ts
- src/drawers/lineDrawer.ts
- test/components/plots/areaPlotTests.ts
- test/components/plots/linePlotTests.ts
- test/tests.js
> [AreaPlot/LinePlot] Restore path class after projection

- quicktests/overlaying/tests/interactions/interaction_hover_scatter.js
Made it hard to tell what was going on.
> Remove shift from interaction_hover_scatter

- plottable.js
- src/interactions/drag/dragInteraction.ts
> Constrain dragEnd() call to available space.

- plottable.js
- src/components/axes/timeAxis.ts
- test/components/timeAxisTests.ts
- test/tests.js
> [TimeAxis] Fixes overlap issues in TimeAxis

- plottable.d.ts
- plottable.js
- src/components/plots/abstractPlot.ts
After some muddling around, removeDataset now is union typed
> [Plot] - unionized removeDataset

- plottable.js
- src/components/axes/numericAxis.ts
- test/components/numericAxisTests.ts
- test/tests.js
> [NumericAxis] Ticks are now only rendered on a valid domain

- plottable.d.ts
- src/components/plots/abstractPlot.ts
I'm mainly having this pull request up so that we can figure out the name of the type as well as the parameters.  Hopefully the parameters are appropriate as discussed.
For now I will base the rest of the needed functions off of this branch for convenience.
> [Plot] - Adding PlotData type

- plottable.d.ts
- plottable.js
- src/dispatchers/abstractDispatcher.ts
- src/dispatchers/keyDispatcher.ts
- src/dispatchers/mouseDispatcher.ts
- test/dispatchers/dispatcherTests.ts
- test/tests.js
`Dispatcher.Mouse` and `Dispatcher.Key` now extend from it.
Changed tests for `AbstractDispatcher`.
> Move AbstractDispatcher to new signature

- plottable.js
- src/drawers/areaDrawer.ts
- test/components/plots/areaPlotTests.ts
- test/tests.js
- typings/d3/d3.d.ts
> [AreaDrawer] - having selector find all paths to include line and area

- plottable.js
- src/components/axes/abstractAxis.ts
- src/components/axes/numericAxis.ts
- test/components/numericAxisTests.ts
- test/tests.js
> [NumericAxis] Display axes properly when min > max

- plottable.js
- src/components/axes/numericAxis.ts
- src/utils/formatters.ts
> [NumericAxis] Address floating point issues with formatters

- plottable.js
- src/utils/formatters.ts
Reverts palantir/plottable#1667
> Revert "[NumericAxis] Address floating point issues with formatters"

- plottable.d.ts
- plottable.js
- src/components/plots/scatterPlot.ts
- src/drawers/circleDrawer.ts
- src/drawers/elementDrawer.ts
- src/reference.ts
- test/drawers/circleDrawerTests.ts
- test/testReference.ts
- test/tests.js
Adding as a subclass to elementDrawer
> [CircleDrawer] - Adding CircleDrawer to the Drawers

- plottable.js
- src/drawers/areaDrawer.ts
- src/drawers/lineDrawer.ts
Fix #1286  and #1649 
Demo fiddle: http://jsfiddle.net/68u6qwnn/2/
> [AreaPlot/LinePlot] Properly set class during projections

- plottable.js
- src/components/axes/categoryAxis.ts
- test/components/categoryAxisTests.ts
- test/tests.js
> [CategoryAxis] Right oriented category axis respects tick marks now

- plottable.d.ts
- plottable.js
- src/dispatchers/mouseDispatcher.ts
- test/dispatchers/dispatcherTests.ts
- test/tests.js
> Add onMouseDown and onMouseUp to Dispatcher.Mouse.

- plottable.js
- src/core/domainer.ts
- test/core/domainerTests.ts
- test/tests.js
> Use valueOf() when comparing to account for Date objects

- plottable.d.ts
- plottable.js
- src/dispatchers/mouseDispatcher.ts
- src/reference.ts
- src/utils/clientToSVGTranslator.ts
- test/dispatchers/dispatcherTests.ts
- test/testReference.ts
- test/testUtils.ts
- test/tests.js
- test/utils/clientToSVGTranslatorTests.ts
Factored the position-translation logic out into a separate class,
so it can be reused.
> Factor out ClientToSVGTranslator.

- plottable.d.ts
- plottable.js
- src/dispatchers/touchDispatcher.ts
- src/reference.ts
- test/dispatchers/touchDispatcherTests.ts
- test/testReference.ts
- test/testUtils.ts
- test/tests.js
- tsd.json
- typings/touch-events/touch-events.d.ts
> Add in Dispatcher.Touch

- plottable.js
- src/components/plots/abstractPlot.ts
Realized that instead of checking if datasetKeys is null, I could just use a default arg
> [Plot] - getAllSelections/getAllPlotData use default arg

- plottable.css
- plottable.js
- src/components/abstractComponent.ts
Select and color using:
```CSS
.plottable .background-fill {
fill: pink;
}
```
Additional selectors can be inserted before "`.background-fill`" to narrow coloring to specific `Component`s.
Close #1725.
> Add a <rect> to Component background so it can be colored.

- plottable.js
- src/components/legend.ts
Instead, users should do it themselves.
Close #1321.
> Legend no longer adds classes to entries based on their data.

- plottable.d.ts
- plottable.js
- src/components/plots/gridPlot.ts
- src/components/plots/rectanglePlot.ts
- src/reference.ts
- test/components/plots/rectanglePlotTests.ts
- test/testReference.ts
- test/tests.js
Still needs unit tests and whatnot, but I wanted to put this out there to kick off a conversation if there is any to be had about the implementation of RectanglePlot (for example, should this be called RectanglePlot?)
Proof of concept with TimeScale and LinearScale/OrdinalScale: http://jsfiddle.net/usv4ombr/2/
Fixes #1709
> [Plots] Implement RectanglePlot, reimplement GridPlot to support non-ordinal scales

- plottable.css
- plottable.d.ts
- plottable.js
- src/components/selectionBoxLayer.ts
- src/core/interfaces.ts
- src/reference.ts
- test/components/selectionBoxLayerTests.ts
- test/testReference.ts
- test/tests.js
This implementation uses a `Component`, `SelectionBoxLayer`, that occupies the entire cell. The selection box drawn by the `Component` does not occupy the whole cell.
<del>Compare to implementation in #1724.</del> Decided to go with this one.
> [WIP] selection-box using Component as a Layer

- plottable.d.ts
- plottable.js
- src/interactions/hoverInteraction.ts
It has been remade into PointerInteraction
> deprecating HoverInteraction

- quicktests/overlaying/tests/basic/categoryAxis_timeAxis.js
- quicktests/overlaying/tests/basic/clustered_bar.js
- quicktests/overlaying/tests/basic/horizontal_clustered_bar.js
- quicktests/overlaying/tests/basic/layout_tables.js
- quicktests/overlaying/tests/basic/legend_basic.js
- quicktests/overlaying/tests/basic/missing_clustered_bar.js
- quicktests/overlaying/tests/basic/missing_stacked_area.js
- quicktests/overlaying/tests/basic/missing_stacked_bar.js
- quicktests/overlaying/tests/basic/ordinal_scale_points_bar.js
- quicktests/overlaying/tests/basic/project_width.js
- quicktests/overlaying/tests/basic/stacked_area.js
- quicktests/overlaying/tests/basic/stacked_bar.js
- quicktests/overlaying/tests/functional/changeData_onClick.js
- quicktests/overlaying/tests/functional/domainChange.js
- quicktests/overlaying/tests/functional/doubleAxes.js
- quicktests/overlaying/tests/functional/titleLegend_change.js
- quicktests/overlaying/tests/interactions/add_time.js
- quicktests/overlaying/tests/interactions/basic_moveToFront.js
- quicktests/overlaying/tests/interactions/interaction_panzoom.js
- quicktests/overlaying/tests/interactions/scale_interactive.js
- quicktests/overlaying/tests/interactions/select_bars.js
- quicktests/overlaying/tests/interactions/select_zoom.js
- quicktests/overlaying/tests/realistic/basic_pie_real.js
- quicktests/overlaying/tests/realistic/rainfall_VerticalBar.js
The API-Break in the conversion of the `merge` API resulted in a bunch of API breaks in our quicktests
> fixing overlay tests

- plottable.d.ts
- plottable.js
- src/dispatchers/mouseDispatcher.ts
- test/dispatchers/mouseDispatcherTests.ts
- test/tests.js
In preparation for DoubleClickInteraction / DblClickInteraction
> [MouseDispatcher] - Adding onDblClick

- plottable.d.ts
- plottable.js
- src/components/interactive/dragBoxLayer.ts
- src/components/interactive/xDragBoxLayer.ts
- src/components/interactive/yDragBoxLayer.ts
- src/components/selectionBoxLayer.ts
- src/reference.ts
- test/components/interactive/xDragBoxLayerTests.ts
- test/components/interactive/yDragBoxLayerTests.ts
- test/testReference.ts
- test/tests.js
Implemented `XDragBoxLayer` and `YDragBoxLayer`.
> XDragBoxLayer and YDragBoxLayer

- plottable.d.ts
- plottable.js
- src/components/selectionBoxLayer.ts
- test/components/selectionBoxLayerTests.ts
- test/tests.js
Has an effective fixed size of zero, but will occupy all offered space.
> SelectionBoxLayer no longer requests extra space.

- tsd.json
- typings/d3/d3.d.ts
- typings/jquery/jquery.d.ts
- typings/mocha/mocha.d.ts
Updated tsd.json to grab latest typings for D3, which contain the merged pull request for interpolated function typing definitions.
> Update tsd.json and other typings

- plottable.d.ts
- src/components/plots/abstractPlot.ts
The build files were not updated when the typings files were not updated...  New branches off of develop will include this diff...
> fixing build files

- plottable.d.ts
- plottable.js
- src/components/axes/timeAxis.ts
- test/components/timeAxisTests.ts
- test/tests.js
Closes #1818 
Changes
- The number of tiers is now an instance variable
- Deleting old axis tiers when creating new ones
- Added unit test for this case
Before: http://jsfiddle.net/pLapukjh/
After: http://jsfiddle.net/pLapukjh/2/
> [Time Axis] We allow for more than 2 tiers

- tslint.json
Disallowing the usage of debuggers in the source code.
> [TSLint Rule] - adding no-debugger rule

- plottable.d.ts
- plottable.js
- src/interactions/dragInteraction.ts
- test/interactions/dragInteractionTests.ts
- test/tests.js
Should be NOQE since it's a rename only.
> Rename constrain() to constrainToComponent().

- plottable.js
- src/components/axes/timeAxis.ts
Now merged to develop.
The hotfix was only applied to the release atm
@jtlan is this how you do it?
> Fix for timeaxis bug

- plottable.js
- src/components/table.ts
> Remove named break in Table code.

- plottable.d.ts
- plottable.js
- src/components/abstractComponent.ts
- src/interactions/abstractInteraction.ts
- src/interactions/clickInteraction.ts
- src/interactions/doubleClickInteraction.ts
- src/interactions/dragInteraction.ts
- src/interactions/keyInteraction.ts
- src/interactions/panZoomInteraction.ts
- src/interactions/pointerInteraction.ts
- test/core/componentTests.ts
- test/tests.js
Removing the hitbox idea entirely since interactions no longer require a hitbox to function.
> [Component] - Removing hitbox

- plottable.d.ts
- plottable.js
- src/reference.ts
- src/utils/callbackSet.ts
- src/utils/set.ts
- test/testReference.ts
- test/tests.js
- test/utils/callbackSetTests.ts
- test/utils/setTests.ts
Became the superclass of CallbackSet...
> Add in shim for ES6 Set.

- plottable.d.ts
- plottable.js
- src/components/plots/areaPlot.ts
- src/components/plots/plot.ts
- src/core/dataset.ts
- test/core/datasetTests.ts
- test/core/metadataTests.ts
- test/tests.js
`_getExtent()` and `_computeExtent()` removed from `Dataset`.
> Plot computes extents instead of Dataset.

- plottable.d.ts
- plottable.js
- src/components/component.ts
- src/core/renderController.ts
- src/core/renderPolicy.ts
- test/globalInitialization.ts
- test/tests.js
Removed an extra loop (commit 1).
Moved it up a level (commit 2):
`Plottable.Core.RenderControllers` --> `Plottable.RenderController` (singleton)
`Plottable.Core.RenderControllers.RenderPolicies` --> `Plottable.RenderPolicies`
> RenderController cleanup

- plottable.d.ts
- plottable.js
- src/components/axes/axis.ts
- src/components/axes/categoryAxis.ts
- src/components/axes/numericAxis.ts
- src/components/axes/timeAxis.ts
- src/components/component.ts
- src/components/dragBoxLayer.ts
- src/components/gridlines.ts
- src/components/interpolatedColorLegend.ts
- src/components/label.ts
- src/components/legend.ts
- src/components/plots/plot.ts
- src/components/selectionBoxLayer.ts
- src/core/renderController.ts
- test/core/componentTests.ts
- test/tests.js
In `component.ts`:
* `public _doRender()` -> `protected _render()`
* `render()` -> `render(immediate: boolean)`
> [apiRefactor] _doRender/render renames

- plottable.d.ts
- plottable.js
- src/components/plots/barPlot.ts
- test/components/plots/barPlotTests.ts
- test/tests.js
`barLabelFormatter` -> `labelFormatter` in `barPlot.ts`
> barLabelFormatter -> labelFormatter

- plottable.d.ts
- plottable.js
- src/components/axes/axis.ts
- src/components/axes/categoryAxis.ts
- src/components/component.ts
- src/components/group.ts
- src/components/interpolatedColorLegend.ts
- src/components/label.ts
- src/components/legend.ts
- src/components/table.ts
- test/components/categoryAxisTests.ts
- test/components/legendTests.ts
- test/components/selectionBoxLayerTests.ts
- test/core/componentGroupTests.ts
- test/core/componentTests.ts
- test/core/tableTests.ts
- test/mocks.ts
- test/testMethods.ts
- test/tests.js
Based in `component.ts` where `_requestedSpace` -> `requestedSpace`
> _requestedSpace -> requestedSpace

- plottable.d.ts
- plottable.js
- src/components/axes/axis.ts
- src/components/component.ts
- src/components/group.ts
- src/components/table.ts
- test/components/selectionBoxLayerTests.ts
- test/core/componentGroupTests.ts
- test/core/tableTests.ts
- test/mocks.ts
- test/tests.js
`_isFixedWidth` -> `hasFixedWidth`
`_isFixedHeight` -> `hasFixedHeight`
> _isFixedWidth/_isFixedHeight -> hasFixedWidth/hasFixedHeight

- quicktests/overlaying/tests/animations/project_scatter.js
- quicktests/overlaying/tests/basic/category_project.js
- quicktests/overlaying/tests/basic/legend_basic.js
- quicktests/overlaying/tests/functional/titleLegend_change.js
- quicktests/overlaying/tests/interactions/basic_moveToFront.js
- quicktests/overlaying/tests/realistic/stocks.js
- quicktests/overlaying/tests/realistic/timeAxis_area_bar.js
> Fix overlaying tests

- plottable.d.ts
- plottable.js
- quicktests/overlaying/tests/basic/grid_plot.js
- quicktests/overlaying/tests/color/interpolatedBar.js
- quicktests/overlaying/tests/functional/base_animator.js
- quicktests/overlaying/tests/functional/categoryFormatter.js
- src/components/plots/plot.ts
- src/scales/categoryScale.ts
- src/scales/interpolatedColorScale.ts
- src/scales/linearScale.ts
- src/scales/modifiedLogScale.ts
- src/scales/quantitativeScale.ts
- src/scales/scale.ts
- src/scales/timeScale.ts
- test/components/plots/barPlotTests.ts
- test/components/timeAxisTests.ts
- test/scales/scaleTests.ts
- test/scales/timeScaleTests.ts
- test/tests.js
Also removed the coercer and no longer accepting coercing (for example passing numbers formatted as strings when numbers are required)
> Removed the any from the scales

- plottable.d.ts
- plottable.js
- src/components/plots/gridPlot.ts
- src/components/plots/rectanglePlot.ts
- src/components/plots/scatterPlot.ts
- test/components/plots/rectanglePlotTests.ts
- test/tests.js
Adding `x1`/`x2`/`y1`/`y2` endpoints to `Plots.Rectangle` as well as `symbol` and `size` to `Plots.Scatter`
> Other properties

- plottable.d.ts
- plottable.js
- src/components/label.ts
- test/components/labelTests.ts
- test/components/numericAxisTests.ts
- test/tests.js
No need to make bulkier objects as they're only css-classes applied on the standard label
> [Label] - TitleLabels and AxisLabels are only css-classes

- src/components/axes/numericAxis.ts
- src/components/gridlines.ts
- src/components/plots/areaPlot.ts
- src/components/plots/barPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/stackedAreaPlot.ts
- src/core/domainer.ts
- src/interactions/panZoomInteraction.ts
- src/scales/interpolatedColorScale.ts
- src/scales/quantitativeScale.ts
- src/scales/scale.ts
Looks like a refactor that went bad. Self explanatory.
> QuantitativeScaleScale to QuantitativeScale in docs

- plottable.d.ts
- src/components/axes/categoryAxis.ts
It only occurred on the below
categoryAxis.tickLabelAngle
> Moving getters before setters

- plottable.d.ts
- plottable.js
- src/scales/scale.ts
Public methods should either return an object or the calling object for chaining
> [Scale] - Appropriate functions now return this

- plottable.d.ts
- plottable.js
- src/components/component.ts
- src/components/dragBoxLayer.ts
- src/components/plots/plot.ts
- test/components/dragBoxLayerTests.ts
- test/components/plots/plotTests.ts
- test/core/componentTests.ts
- test/testMethods.ts
- test/tests.js
`public clipPathEnabled` -> `protected _clipPathEnabled`
> public clipPathEnabled -> protected _clipPathEnabled

- plottable.d.ts
- plottable.js
- src/components/componentContainer.ts
- src/core/renderController.ts
- test/core/renderControllerTests.ts
- test/tests.js
Put back the original (somewhat wonky) logic. We'll go back and streamline it later.
> Restore original RenderController logic.

- plottable.d.ts
- src/components/component.ts
- src/components/dragBoxLayer.ts
- src/core/dataset.ts
- src/dispatchers/keyDispatcher.ts
- src/dispatchers/mouseDispatcher.ts
- src/dispatchers/touchDispatcher.ts
- src/interactions/clickInteraction.ts
- src/interactions/dragInteraction.ts
- src/interactions/keyInteraction.ts
- src/interactions/pointerInteraction.ts
> Change callback return types from any to void.

- plottable.d.ts
- plottable.js
- src/animators/rectAnimator.ts
- src/components/plots/barPlot.ts
- src/components/plots/clusteredBarPlot.ts
- src/components/plots/gridPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/plot.ts
- src/components/plots/rectanglePlot.ts
- src/components/plots/stackedAreaPlot.ts
- src/components/plots/stackedBarPlot.ts
- src/components/plots/stackedPlotUtils.ts
- src/components/plots/xyPlot.ts
- src/core/interfaces.ts
- src/drawers/arcDrawer.ts
- src/drawers/drawer.ts
- src/drawers/rectDrawer.ts
- test/core/metadataTests.ts
- test/drawers/drawerTests.ts
- test/tests.js
This field just isn't really something that should be exposed to the user.
> [Plot] - Remove PlotMetadata

- plottable.d.ts
- plottable.js
- src/animators/rectAnimator.ts
- src/components/plots/barPlot.ts
- src/components/plots/clusteredBarPlot.ts
- src/components/plots/gridPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/plot.ts
- src/components/plots/rectanglePlot.ts
- src/components/plots/stackedAreaPlot.ts
- src/components/plots/stackedBarPlot.ts
- src/components/plots/stackedPlotUtils.ts
- src/components/plots/xyPlot.ts
- src/core/interfaces.ts
- src/drawers/arcDrawer.ts
- src/drawers/drawer.ts
- src/drawers/rectDrawer.ts
- test/components/plots/clusteredBarPlotTests.ts
- test/components/plots/stackedAreaPlotTests.ts
- test/components/plots/stackedBarPlotTests.ts
- test/components/plots/stackedPlotTests.ts
- test/core/metadataTests.ts
- test/drawers/drawerTests.ts
- test/tests.js
Something that was exposed to the user for not necessarily good reason... has now... disappeared!
PlotMetadata is no longer a thing.
> [Plot] - Remove plot metadata

- Gruntfile.js
- test/components/labelTests.ts
- test/components/legendTests.ts
- test/components/plots/stackedPlotTests.ts
- test/globalInitialization.ts
- test/tests.js
Unskips few tests. Created this now to unblock #2092
Part of #1921 
- Upgraded Firefox and Chrome on SauceLabs to the latest version
- Increased tolerance of FireFox pixel precision to 2
> Unskip tests

- plottable.js
- src/components/axes/categoryAxis.ts
- src/components/axes/numericAxis.ts
- src/components/axes/timeAxis.ts
- src/components/component.ts
- src/components/label.ts
- src/components/plots/barPlot.ts
- src/components/plots/xyPlot.ts
- src/components/table.ts
- src/drawers/areaDrawer.ts
- src/scales/interpolatedColorScale.ts
- src/utils/domUtils.ts
- src/utils/utils.ts
- test/components/labelTests.ts
- test/components/numericAxisTests.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/gridPlotTests.ts
- test/components/plots/rectanglePlotTests.ts
- test/components/plots/scatterPlotTests.ts
- test/components/timeAxisTests.ts
- test/core/tableTests.ts
- test/testMethods.ts
- test/tests.js
- test/utils/domUtilsTests.ts
Solved multiple consecutive whitespace issues
```regex
^([\s]+[^\s\*]+.* ) 
$1
```
> Double space fix

- plottable.d.ts
- plottable.js
- src/components/label.ts
- test/components/labelTests.ts
- test/tests.js
..the same way that the old constructor used to take the orientation as a parameter.
Close #2130.
> Label constructor now takes angle as an optional parameter.

- plottable.d.ts
- plottable.js
- src/components/dragBoxLayer.ts
Since this is just a getter for an existing variable, I think it's probably [NOQE].
> Retrieve internal Interaction of DragBoxLayer with dragInteraction()

- plottable.css
Quite a few declarations that we don't really document anywhere.
We should think about a way to document this better if possible
> [Plottable.css] - Cleaning useless declarations

- plottable.d.ts
- plottable.js
- src/components/axes/numericAxis.ts
- test/components/numericAxisTests.ts
- test/tests.js
The function actually did absolutely nothing.  If we need to add the concept in, we can add it in at a later date.
> removing showEndTickLabel

- plottable.d.ts
- plottable.js
- src/components/plots/barPlot.ts
- src/components/plots/rectanglePlot.ts
- src/drawers/rectangleDrawer.ts
- src/reference.ts
Abbreviation was bad... Let's stop abbreviating
> [Drawers.Rect] - Drawers.Rect -> Drawers.Rectangle

- plottable.d.ts
- plottable.js
- src/components/plots/barPlot.ts
- src/components/plots/stackedBarPlot.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/clusteredBarPlotTests.ts
- test/components/plots/stackedBarPlotTests.ts
- test/tests.js
> [2206rf] renamed baseline() to baselineValue()

- plottable.d.ts
- plottable.js
- src/components/plots/xyPlot.ts
- test/components/plots/xyPlotTests.ts
- test/tests.js
> Add a getter and some unit tests for XYPlot.autorange()

- plottable.d.ts
- plottable.js
- src/components/plots/barPlot.ts
- test/components/plots/barPlotTests.ts
- test/tests.js
> [2204rf] added orientation() to the Bar Plot

- plottable.d.ts
- src/scales/scale.ts
> PaddingExceptionProvider can only take a quantitative scale now

- tsd.json
No actual diff in d3.d.ts since the PR I sent to DefinitelyTyped
was the latest version...
> Update d3 definitions to latest hash.

- plottable.js
- src/components/plots/areaPlot.ts
> Using Enum instead of string for Plot.Animator.MAIN

- plottable.js
- src/core/renderController.ts
- src/utils/stackedUtils.ts
Some variables were underscored incorrectly and thus are fixed here
> Underscore fixes

- plottable.d.ts
- plottable.js
- src/components/legend.ts
- test/components/legendTests.ts
- test/tests.js
By definition, a Legend is a visualization of a colorScale.  It should be named such
> [Legend] - legend.scale -> legend.colorScale

- plottable.d.ts
- plottable.js
- src/dispatchers/dispatcher.ts
- src/dispatchers/keyDispatcher.ts
- src/dispatchers/mouseDispatcher.ts
- src/dispatchers/touchDispatcher.ts
- test/dispatchers/dispatcherTests.ts
- test/tests.js
API Changes:
* `dispatcher._event2Callback` has been renamed to `dispatcher._eventToCallback`
> _event2Callback -> _eventToCallback

- plottable.d.ts
- plottable.js
- src/interactions/dragInteraction.ts
- src/interactions/panZoomInteraction.ts
- test/interactions/dragInteractionTests.ts
- test/tests.js
API Changes:
* `dragInteraction.constrainToComponent()` has been renamed to `dragInteraction.constrainedToComponent()`
> [Interactions.Drag] - constrainToComponent -> constrainedToComponent

- src/components/plots/barPlot.ts
- test/components/plots/barPlotTests.ts
- test/tests.js
We done goofed. Modifying nouns should be singular: http://en.wikipedia.org/wiki/Noun_adjunct
No one says "stops sign" for example.
> "labelsFormatter" --> "labelFormatter"

- plottable.d.ts
- plottable.js
- src/components/plots/areaPlot.ts
- src/components/plots/plot.ts
- test/components/plots/areaPlotTests.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/clusteredBarPlotTests.ts
- test/components/plots/linePlotTests.ts
- test/components/plots/piePlotTests.ts
- test/components/plots/plotTests.ts
- test/components/plots/rectanglePlotTests.ts
- test/components/plots/scatterPlotTests.ts
- test/components/plots/stackedBarPlotTests.ts
- test/core/metadataTests.ts
- test/drawers/lineDrawerTests.ts
- test/tests.js
API Changes:
* `plot.getAllSelections()` has been renamed to `plot.selections()`
Closes #2199
> [Plot] - getAllSelections -> selections

- plottable.d.ts
- plottable.js
- src/components/plots/areaPlot.ts
- src/components/plots/barPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/piePlot.ts
- src/components/plots/plot.ts
- src/components/plots/rectanglePlot.ts
- src/components/plots/scatterPlot.ts
- test/components/plots/plotTests.ts
- test/components/plots/xyPlotTests.ts
- test/drawers/lineDrawerTests.ts
- test/scales/linearScaleTests.ts
- test/tests.js
The function creates a new instance every time.  The "get" prefix here is really confusing
API Changes:
* `plot._getDrawer()` has been renamed to `plot._createDrawer()`
> [Plot] - `_getDrawer` -> `_createDrawer`

- quicktests/overlaying/tests/basic/negative_stacked_bar.js
- quicktests/overlaying/tests/functional/titleLegend_change.js
- quicktests/overlaying/tests/interactions/interaction_BarHover.js
- quicktests/overlaying/tests/interactions/interaction_hover_scatter.js
- quicktests/overlaying/tests/realistic/basic_pie_real.js
- quicktests/overlaying/tests/realistic/stocks.js
- quicktests/overlaying/tests/realistic/symbols.js
* Switched back to using `TitleLabel`.
* Cleaned a mis-switch involving a `Key` `Interaction`
> Fix overlaying tests to work on both develop and master

- plottable.d.ts
- plottable.js
- src/utils/clientToSVGTranslator.ts
- src/utils/colorUtils.ts
- src/utils/domUtils.ts
- src/utils/map.ts
- src/utils/mathUtils.ts
- src/utils/set.ts
Part of #2265 
Did not know what to say for `colorUtils.colorTest()`
> Utils docs

- plottable.d.ts
- plottable.js
- src/components/plots/areaPlot.ts
- src/components/plots/barPlot.ts
- src/components/plots/clusteredBarPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/piePlot.ts
- src/components/plots/plot.ts
- src/components/plots/scatterPlot.ts
- src/components/plots/stackedAreaPlot.ts
Mainly peeling the scales from the constructor docs and adding constructor docs to inform what the class is
> [Plots] - Adding docs

- src/animators/animator.ts
- src/axes/axis.ts
- src/components/component.ts
- src/components/componentContainer.ts
- src/core/config.ts
- src/core/dataset.ts
- src/core/formatters.ts
- src/core/interfaces.ts
- src/core/renderController.ts
- src/core/renderPolicy.ts
- src/core/symbolFactories.ts
- src/core/version.ts
- src/dispatchers/dispatcher.ts
- src/drawers/drawer.ts
- src/interactions/interaction.ts
- src/plots/plot.ts
- src/plots/xyPlot.ts
- src/scales/quantitativeScale.ts
- src/scales/scale.ts
- src/scales/tickGenerators.ts
- src/utils/arrayUtils.ts
- src/utils/callbackSet.ts
- src/utils/set.ts
- src/utils/stackingUtils.ts
- src/utils/windowUtils.ts
Part of #1942
As per a conversation with @bluong, we have two options
- Indent everything properly
- Consider `module Plottable {` to be an exception
The advantage of the former is that of consistency. The advantage of the latter is horizontal space saving. Also, as we can see, every single file begins with `module Plottable {`. This suggests that probably the same behavior can be achieved through tooling. I looked into it for a while and could not figure out how to wrap everything in a module, but if we manage to do that, then the change will be super easy, just delete 2 lines.
Either way we go, we need to be consistent across files.
> Indentation

- plottable.d.ts
- plottable.js
- src/plots/piePlot.ts
- test/plots/piePlotTests.ts
- test/tests.js
Adds `.entitiesAt(point)` to `Plots.Pie`
Fiddle: http://jsfiddle.net/ogj7qLxw/2/
> [Plots.Pie] Add .entitiesAt() to Plots.Pie

- license_header.txt
- plottable.js
[NOQE] because no code changes.
> Updated copyright date in license header.

- .eslintrc
Accidentally merge resolved incorrectly.  This should fix that.
> [ESLint] - Merge resolution fix

- plottable.js
Not sure why this was not included into develop yet.
> [build] Uncompiled file on develop

- plottable.d.ts
- plottable.js
- src/dispatchers/mouseDispatcher.ts
- src/utils/clientToSVGTranslator.ts
- test/dispatchers/mouseDispatcherTests.ts
> Ignore clicks not directed at Plottable graphs. Fixes #2142

- plottable.js
- src/plots/piePlot.ts
- test/plots/piePlotTests.ts
> "chart" --> "plot" in Plots.Pie.

- plottable.d.ts
- plottable.js
- src/axes/axis.ts
- src/axes/timeAxis.ts
- test/axes/baseAxisTests.ts
- test/axes/categoryAxisTests.ts
- test/axes/numericAxisTests.ts
> Rename tickLength() to innerTickLength()

- package.json
We need this to get our Travis working again because of https://github.com/jdcataldo/grunt-mocha-phantomjs/issues/36
> Upgrade grunt-mocha-phantomjs to 0.6.2

- package.json
Reverts palantir/plottable#2467
> Revert "Upgrade grunt-mocha-phantomjs to 0.6.2"

- Gruntfile.js
Part of #2445
BLUF: Nothing has been changed (functionally). Things have moved from one place to another. Prereq for deeper purge
Done:
- Renamed variables
- Extracted configuration objects
- Inlined variables
- Fixed indentation
Not done:
- Deleting tasks that are not used anymore
- Improve the minification 
- Improve the run time
> Gruntfile refactor

- plottable.d.ts
- plottable.js
- src/plots/plot.ts
- src/plots/rectanglePlot.ts
- src/plots/segmentPlot.ts
- test/plots/rectanglePlotTests.ts
- test/plots/segmentPlotTests.ts
> Fix autoranging on Plots.Segment and Plots.Rectangle (alternate take)

- README.md
for mac users, try to avoid the print and scan dance.
> add helpful comment on signing CLA

- plottable.js
- src/components/legend.ts
- test/components/legendTests.ts
- typings/d3/d3.d.ts
index was wrong due to nested selection
closes #2106
> 2106 Legend.symbol() doesn't pass in index correctly

- plottable.js
- src/plots/piePlot.ts
- test/plots/piePlotTests.ts
Also fixed:
* Updating data doesn't create multiple sets of labels.
* Updating data recomputes slices before rendering.
... both of which were found in the course of investigating the main bug.
Close #2483.
> [Plots.Pie] Labels are removed when labelsEnabled(false)

- plottable.d.ts
- plottable.js
- src/plots/piePlot.ts
- test/plots/piePlotTests.ts
> add labelFomatter for pie plot

- plottable.js
- src/scales/modifiedLogScale.ts
- test/scales/modifiedLogScaleTests.ts
closes #2387
http://jsfiddle.net/ztsai/1zfz0tg2/1/
> add more ticks to the linear part of modified log scale

- plottable.js
- src/plots/piePlot.ts
- test/plots/piePlotTests.ts
closes #2491
before: http://jsfiddle.net/pghLh8da/4/
after: http://jsfiddle.net/pghLh8da/3/
> fix pie chart selection bug

- test/utils/arrayUtilsTests.ts
- test/utils/callbackSetTests.ts
- test/utils/clientToSVGTranslatorTests.ts
- test/utils/colorUtilsTests.ts
- test/utils/domUtilsTests.ts
- test/utils/mapTests.ts
- test/utils/mathUtilsTests.ts
- test/utils/setTests.ts
- test/utils/stackingUtilsTests.ts
- test/utils/windowUtilsTests.ts
Starting on the tests directory, specificially utils.
> [TSLint] - enforce no-var-keyword on utilsTests

- plottable.d.ts
- plottable.js
- src/dispatchers/keyDispatcher.ts
- src/interactions/keyInteraction.ts
- test/dispatchers/keyDispatcherTests.ts
- test/interactions/keyInteractionTests.ts
- test/testMethods.ts
added key interaction api:
```onKeyRelease(keyCode: number, callback: KeyCallback)```
```offKeyRelease(keyCode: number, callback: KeyCallback)```
example: http://jsfiddle.net/5c6djgco/2/
closes #2393
> add api for keyup event listener

- Gruntfile.js
> add iPad to Sauce tests

- plottable.js
- src/interactions/panZoomInteraction.ts
- test/interactions/panZoomInteractionTests.ts
closes #2510 
http://jsfiddle.net/ztsai/w82shn5r/
> check touch positions for zooming in iPad

- plottable.js
- src/plots/piePlot.ts
- test/plots/piePlotTests.ts
closes #2556 
demo: http://jsfiddle.net/ztsai/k5yaLhyp/1/
> only draw labels for valid data in pie plot

- plottable.js
- src/dispatchers/touchDispatcher.ts
- test/dispatchers/touchDispatcherTests.ts
closes #2452
demo: http://jsfiddle.net/ztsai/gzLqekvh/5/
> prevent click and drag interactions from triggering through overlays

- plottable.d.ts
- plottable.js
- src/components/table.ts
- src/plots/piePlot.ts
- src/plots/waterfallPlot.ts
- src/scales/categoryScale.ts
- src/scales/colorScale.ts
- src/scales/interpolatedColorScale.ts
- src/scales/modifiedLogScale.ts
- src/scales/quantitativeScale.ts
- src/scales/scale.ts
- src/scales/tickGenerators.ts
- src/scales/timeScale.ts
- test/testMethods.ts
Main things to look at are `waterfallPlot.ts` and `table.ts`
Everything else is either removing tslint-disable flags or straight `var` to `let`.
> No var cleanups

- bower.json
- package.json
Standardizing and clarifying the description we use for the library.
> Standardize the tagline.

- plottable.d.ts
- plottable.js
- src/plots/rectanglePlot.ts
- test/plots/rectanglePlotTests.ts
add ```entitiesIn(bound) ``` / ```entitiesIn(xRange, yRange)``` for rectangle plot
demo: http://jsfiddle.net/ztsai/0jtt5crx/3/
closes: #2570
> add entitiesIn() for Rectangle plot

- plottable.d.ts
- plottable.js
- src/plots/segmentPlot.ts
- test/plots/segmentPlotTests.ts
add entitiesIn(bound) / entitiesIn(xRange, yRange) for segment plot
demo: http://jsfiddle.net/ztsai/ydm4znfs/5/
closes: #2572
> add entitiesIn() for segment plots

- plottable.d.ts
- plottable.js
- src/plots/scatterPlot.ts
- test/plots/scatterPlotTests.ts
closes: #2569
demo: http://jsfiddle.net/fa3mjzew/4/
> add entitiesAt() for scatter plot

- plottable.css
- plottable.d.ts
- plottable.js
- src/drawers/arcDrawer.ts
- src/drawers/arcOutlineDrawer.ts
- src/plots/piePlot.ts
- src/reference.ts
- test/plots/piePlotTests.ts
closes #2492 
demo: http://jsfiddle.net/ztsai/g5spysum/7/
> draw stroke with an additional path for pie plot

- plottable.d.ts
- plottable.js
- src/plots/piePlot.ts
- test/plots/piePlotTests.ts
closes #2611 
http://jsfiddle.net/ztsai/k5yaLhyp/7/
> skip negative values in pie plot

- plottable.d.ts
- plottable.js
- src/components/component.ts
- test/components/componentTests.ts
> renderTo() now accepts DOM nodes

- test/plots/rectanglePlotTests.ts
Part of #2636
I will be doing multiple passes because I will get more context (and better sense of best practices) by refactoring other files. However, please flag anything that seems unusual.
- Correct semantics of the test titles
> Refactor rectangle plot tests - Pass 1

- test/scales/modifiedLogScaleTests.ts
> Refactor modified log scale tests - Pass 1

- plottable.d.ts
- plottable.js
- src/core/formatters.ts
- test/core/formattersTests.ts
> Formatter Unit test refactor

- Gruntfile.js
- plottable.js
- src/plots/rectanglePlot.ts
- src/plots/wheelPlot.ts
http://jsfiddle.net/jmnwbrzq/
It was bothering me that rectangle and wheel rendered black, so I added the line to fix it.
I didn't add tests because I didn't see tests for this anywhere else. But I can if I should.
> Rectangle fill and Wheel fill to Plottable-Blue

- test/scales/tickGeneratorsTests.ts
> TickGeneratorsTests refactor

- test/components/groupTests.ts
- test/testMethods.ts
New structure looks like this:
Close #2711.
> Test Refactor: Groups

- .gitignore
As listed here
https://code.visualstudio.com/updates ("Renamed VS Code Settings Folder" section)
Visual Studio Code has renamed its configuration directory to be .vscode
Ignoring this to not see annoying git messages
> update ignore file to ignore changed vsc filename

- test/interactions/pointerInteractionTests.ts
> Refactor pointer interaction tests - Pass 1

- plottable.js
Develop's version is at 1.10 for some reason...
> bumping version number

- test/dispatchers/mouseDispatcherTests.ts
> Refactor mouse dispatcher tests - Pass 1

- Gruntfile.js
The tasks are not part of any of the task workflow, and it seems that no one has used these commands.  Removing.
> [Gruntfile] - removing never-used sublime commands

- test/core/symbolFactoriesTests.ts
- test/testReference.ts
> add unit test for SymbolFactories

- test/plots/waterfallPlotTests.ts
> [Plots.Waterfall] - Refactor tests

- test/axes/axisTests.ts
- test/testReference.ts
> [Axis Tests] - Rework

- test/axes/timeAxisTests.ts
> [TimeAxis Tests] - Rework

- test/plots/areaPlotTests.ts
- test/plots/linePlotTests.ts
- test/testMethods.ts
> areaPlotTests refactor

- plottable.css
- plottable.js
- src/components/interpolatedColorLegend.ts
- test/components/interpolatedColorLegendTests.ts
add title to each swatch in `interpolatedColorLegend` if `Configs.ADD_TITLE_ELEMENTS` is true
demo: http://jsfiddle.net/ztsai/r3ozqxre/ http://jsfiddle.net/ztsai/r3ozqxre/3/
closes #2887
> add title to swatches in interpolatedColorLegend

- plottable.js
- src/components/interpolatedColorLegend.ts
- test/components/interpolatedColorLegendTests.ts
...but it's actually just a large amount of very skinny swatches.
before: http://jsfiddle.net/j5b9f60c/57/
after http://jsfiddle.net/j5b9f60c/58/
> Use a gradient for InterpolatedColorLegend instead of swatches

- .eslintrc
- quicktests/exampleUtil.js
Add utility function to create random data with name, x, and y fields. Name is selected at random from the set "A" - "Z"
and will be unique in the returned array.
Supports consideration of object constancy in quicktests
.eslintrc modified so this function may be used without declaration without raising an error
> Add utility function to create random data with name, x, and y fields

- plottable.d.ts
- src/interactions/panZoomInteraction.ts
Forgot this file when submitting #2931
> [PanZoomInteraction] - nesting module into Plottable.Interactions

- test/plots/rectanglePlotTests.ts
Most of the functionality is fine, but some pieces needed to be more aligned with guidelines in order to grep correctly + have less fragility.
Part of #2636 
Test screenshot:
> [RectanglePlotTests] - Rework Part 2

- test/plots/segmentPlotTests.ts
Small cleanup regarding adhering to guidelines and making tests less fragile.
Part of #2636 
Test screenshot:
> [SegmentPlotTests] - rework part 2

- plottable.js
- src/components/table.ts
- test/components/tableTests.ts
fixes #2896 
fixes #2897 
http://jsfiddle.net/9f87y5hm/
uncomment in window.onload() to test all things i'm claiming to fix with this PR
> Row/Column + Padding/Weight don't accept Infinity or negative numbers

- test/components/gridlinesTests.ts
> refactor gridlinesTests

- test/components/legendTests.ts
> refactor legendTests

- test/components/interpolatedColorLegendTests.ts
part of #2625 
- break down tests into subgroups
- change all `_content` to `.content()`
- refactor similar tests into loop
- update test names
- `let` -> `const`
> refactor InterpolatedColorLegendTests

- test/components/labelTests.ts
> refactor LabelTests

- test/drawers/drawerTests.ts
- test/scales/linearScaleTests.ts
Only the refactor for the parent `Drawer` class' tests (I'll do the subclasses in a separate PR).
Once again, a number of methods were not being tested, and are now being tested using the power of a mock class.
Part of #2622.
> [Testing Audit] parent Drawer tests

- plottable.js
- src/components/component.ts
- test/components/componentTests.ts
Previously was set to true and never reset!
Blocking changes on #2984.
Close #3004.
> Set _isTopLevelComponent based on whether the root node is an SVG

- plottable.d.ts
- plottable.js
- src/interactions/pointerInteraction.ts
- test/interactions/pointerInteractionTests.ts
pointerIneraction part of #2416 
revert #2910
> pointerInteraction should not trigger under overlay

- .editorconfig
- .tslintrc
- README.md
- bower.json
> EditorConfig, whitespace cleanup, README edits
