palantir/plottable

- quicktests/js/formatter.js
`.map()` makes so much more sense....
> Update formatter quicktest to not deep-clone data

- README.md
Chartographer is becoming disbanded.  We should remove the mention from our readme.
> Removing mention of chartographer from readme

- plottable.d.ts
- plottable.js
- src/components/axes/categoryAxis.ts
- src/components/plots/barPlot.ts
- src/components/plots/clusteredBarPlot.ts
- src/components/plots/gridPlot.ts
- src/scales/ordinalScale.ts
- test/components/categoryAxisTests.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/clusteredBarPlotTests.ts
- test/components/plots/stackedBarPlotTests.ts
- test/tests.js
After thinking about Ordinal Scales, it seems to be this:
Bands mode is useful for certain situations, and points mode is useful for certain situation.  However, bands mode scales the domain value to the start of the band, when interacting with the band usually makes more sense when the value is set to the center of the band.  Thus, we need to make a decision.  Does it make more sense for the default to scale to the center of the band (more work for placing the band) or does it make more sense to default to the start of the band (more work for interacting with the band).  Either way, another issue is that regardless of which we choose, we have to think about an easy way to do the other.
The next step of the revamp is likely to hide away setting the rangeType from the user.  We should …
> Ordinal scale bands revamp

- plottable.js
- src/components/plots/barPlot.ts
This needed to exist before since we needed to guard for default accessors being invalid.  This is no longer the case, so this somewhat hefty computation can be removed.
QE: We probably want to regression pass over this for specifically bar charts.
> [BarPlot] - Remove checking if data is invalid for barPixelWidth

- plottable.js
- src/scales/ordinalScale.ts
The error doesn't make too much sense since we don't have a capability to set the innerPadding/outerPadding before this is called in the first place.  Also moving the scale validation to have a default paramter
> [OrdinalScale] - Cleaning up the constructor

- plottable.d.ts
- plottable.js
- src/components/axes/timeAxis.ts
- src/components/plots/abstractPlot.ts
- src/components/plots/abstractStackedPlot.ts
- src/components/table.ts
- src/core/animator.ts
- src/core/broadcaster.ts
- src/core/dataset.ts
- src/core/interfaces.ts
- src/drawers/abstractDrawer.ts
- src/interactions/drag/dragBoxInteraction.ts
- src/interactions/hoverInteraction.ts
- src/scales/interpolatedColorScale.ts
- src/scales/tickGenerators.ts
- src/utils/formatters.ts
- test/components/timeAxisTests.ts
- test/tests.js
Now that Typescript has added the type feature in Typescript 1.4, we can make use of it: http://blogs.msdn.com/b/typescript/archive/2015/01/16/announcing-typescript-1-4.aspx
The type feature allows for Type aliasing which means that you can alias a type into a different name.
One simple example can be to alias
`type Phrase = string;`
so that you can use the term `phrase` as a replacement for the term `string` throughout the codebase, which is very nice for semantical reasoning.
A more useful example can be to alias
`type InteractionCallback = (data: any) => any;`
so that we can now alias callbacks with hard-to-reason-about signatures to a concise, short term
A more interesting example can be to alias
`type Person = {
firstName: string;
lastName: string;
}`
so that we can now encapsulate …
> [TS1.4] - Utilizing the 'type' feature in Typescript

- plottable.js
- src/components/axes/timeAxis.ts
(from an earlier state of **develop**)
We were splicing/etc, when the correct tick marks were already generated.
Close #1606.
> Clearer tick generation on Axis.Time

- plottable.d.ts
- plottable.js
- src/dispatchers/mouseDispatcher.ts
- src/interactions/abstractInteraction.ts
- src/interactions/hoverInteraction.ts
- src/utils/domUtils.ts
- test/dispatchers/dispatcherTests.ts
- test/interactions/hoverInteractionTests.ts
- test/tests.js
Only one is created per \<svg\>.
Now detects mouse position by drawing a test rectangle,
which allows it to account for CSS zoom and the IE9 zoom bug (#1490).
AbstractDispatcher to follow.
> Convert Dispatcher.Mouse to a <svg>-wide Dispatcher.

- plottable.d.ts
- plottable.js
- src/core/broadcaster.ts
- src/core/dataset.ts
- src/core/resizeBroadcaster.ts
- src/scales/abstractScale.ts
- test/components/plots/plotTests.ts
- test/core/broadcasterTests.ts
- test/core/componentTests.ts
- test/core/datasetTests.ts
- test/scales/scaleTests.ts
- test/tests.js
Previously: `Broadcasters` had-a `Listenable`, which had-a reference to the same `Broadcaster`. This was silly and prevented the use of multiple
`Broadcasters` on the same object.
Now we can use generic typing to convey more information about what the `Broadcaster` is broadcasting.
Close #1604.
> Convert Broadcaster to use generics, remove Listenable.

- plottable.d.ts
- plottable.js
- src/core/broadcaster.ts
- src/dispatchers/mouseDispatcher.ts
- test/dispatchers/dispatcherTests.ts
- test/tests.js
And remove them when all callbacks are removed.
Made callbacks not trigger if measurement fails.
Made `Dispatcher.Mouse`'s `Broadcaster` private.
> Add event listeners on registering callbacks

- plottable.js
- src/components/axes/categoryAxis.ts
- test/components/categoryAxisTests.ts
- test/tests.js
The textFits parameter currently determines if the text labels on a categoryAxis can fit there.  However the calculation is... incorrect.
It used to read - If I have 1 wrapped line and I am not not an empty string, then I fit
It should read - If I have 1 wrapped line and I am not an empty string, then I fit
In short, confusing double negative is confusing
Fixes #1511
> [CategoryAxis] - Correcting textFits parameter for space calculations

- plottable.d.ts
- plottable.js
- src/core/broadcaster.ts
- test/core/broadcasterTests.ts
- test/tests.js
... instead of as an array. This change forces us to choose a `this`-context for the callbacks; The `this`-context passed to the callbacks is the `Broadcaster`'s "listenable".
Close #1583.
> Pass arguments to Broadcaster callbacks one at a time

- plottable.d.ts
- plottable.js
- src/components/plots/abstractPlot.ts
- test/components/plots/areaPlotTests.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/gridPlotTests.ts
- test/components/plots/linePlotTests.ts
- test/components/plots/piePlotTests.ts
- test/components/plots/plotTests.ts
- test/tests.js
Adding optional parameters to the API point getAllSelections to look like
`getAllSelections(datasetKeys?: string | string[])`
The above API endpoint will allow users to retrieve all of the selections for the specified dataset(s).
NOTE: One possible API would be to change getAllSelections to
`getAllSelections(...datasetKeys?: string[] | string[][])`
This would allow input like
`getAllSelections("a", "b", "c")` instead of forcing to use an array.  I still would want the array API endpoint but this is optional.
NOTE: I'm currently in consideration of a second optional boolean argument `exclude` which will return the selections of all datasets excluding the ones specified by the first datasetKeys argument
> [Plot] - getAllSelections() with dataset key params

- plottable.d.ts
- plottable.js
- src/components/plots/gridPlot.ts
Used to create an ElementDrawer that sets its own svgElement to "rect"
> [GridPlot] - getDrawer now returns a RectDrawer

- plottable.js
- src/components/axes/categoryAxis.ts
- test/components/categoryAxisTests.ts
- test/tests.js
It appears that the crux of the matter is that SVGTypewriter does not really work for rotated text as far as I know, so in cases where the text is rotated, I am taking an approach where adjustments to width requested are made based on the angle of the tick label, and then flipping the width and height results at the end of _measureTicks.
JSFiddle of fix: http://jsfiddle.net/xcgjf426/3/
Fix #1526
> [CategoryAxis] Make rotated ticks wrap less aggressively

- plottable.js
- src/components/axes/categoryAxis.ts
Reversed decision to put a ! in front of the textFits calculation.
Fixed actual tick label height calculation.
Placing HACKHACK where wrapper  will report incorrect responses for negative width/height results
> Text category axis fix

- package.json
PhantomJS results sometimes in a cyclical structure error when attempting to use assert.includeMembers in mocha.  Upgrading should solve the issue.
> Upgrading grunt-mocha-phantomjs

- plottable.d.ts
- plottable.js
- src/components/plots/abstractPlot.ts
- test/components/plots/plotTests.ts
- test/tests.js
The new signature for getAllSelections after this pull request should be
```typescript
public getAllSelections(datasetKeys?: string | string[], exclude = false): D3.Selection
```
An exclude argument is added as a parameter that defaults to false that can be set to true if the user wants to retrieve all selections excluding the ones specified in datasetKeys.
> [Plot] - Adding exclude argument to getAllSelections

- plottable.d.ts
- plottable.js
- src/components/plots/abstractPlot.ts
- src/core/interfaces.ts
- src/drawers/abstractDrawer.ts
- src/drawers/arcDrawer.ts
- src/drawers/areaDrawer.ts
- src/drawers/lineDrawer.ts
With the idea of the `project` call, users of Plottable are able to set the attributes of the plot through the use of accessors and scales.  However, the exact way that Plottable computes these attributes is hidden from the user.
For example, consider the call
`plot.project("x", "x", xScale)`
It is hidden from the user that in order to compute the x attribute of the rendered plot the fact that the "x" attribute is queried per datum and scaled with the xScale to find the pixel point that the datum will render to.
This is incredibly important for plots like `Plot.Scatter` to function correctly as there must be a way to map from a datum to a pixel position.
This pull request is an attempt at higher transparency between the user and the plot, letting the user query the following API endpoint …
> [Plot] - Adding generateProjectors() API

- plottable.js
- src/utils/symbolGenerators.ts
- test/testReference.ts
- test/tests.js
- test/utils/symbolGeneratorsTests.ts
Throws an error if an invalid symbol type is given.  Default sizeFactor (only will be used after the verification)
> [Hotfix][SymbolGenerators] - d3 symbol type verification

- plottable.d.ts
- plottable.js
- src/interactions/pointerInteraction.ts
- src/reference.ts
- test/interactions/pointerInteractionTests.ts
- test/testReference.ts
- test/tests.js
Similar to the old `Interaction.Mousemove`, produces pixels whenever the pointer (mouse or touch), enters the `Component`, moves, or exits the `Component`.
> Add Interaction.Pointer.

- plottable.d.ts
- plottable.js
- src/components/abstractComponent.ts
- src/components/componentGroup.ts
- test/core/componentGroupTests.ts
- test/scales/scaleTests.ts
- test/tests.js
Replacing the `merge` API with an `above`/`below` API so users can make sense of where they are placing their components in regards to layering them on top of each other.
Fixes #1037
> [Component] - Replace `merge` with `above`/`below`

- plottable.d.ts
- plottable.js
- src/interactions/clickInteraction.ts
- src/interactions/doubleClickInteraction.ts
- src/reference.ts
As `Interaction.Click` is going to be rearchitected, we should shelve off `Interaction.DoubleClick` to use the old architecture to retain functionality.
> [Interaction.DoubleClick] - Removing Click hierarchy

- plottable.d.ts
- plottable.js
- src/interactions/dragInteraction.ts
- test/interactions/dragInteractionTests.ts
- test/tests.js
Important for panning to feel intuitive.
Moved all `assert` statements corresponding to constraint to a new test.
> Allow disabling of constraint functionality.

- plottable.d.ts
- plottable.js
- src/drawers/symbolDrawer.ts
- test/components/plots/scatterPlotTests.ts
- test/tests.js
`Drawer.Element` has functionality that should have been picked up in `Drawer.Symbol` but due to the lack of extension, that was unfortunately not picked up.  Now the hierarchy is made.
Fixes #1771
> [SymbolDrawer] - Extends from ElementDrawer

- plottable.d.ts
- plottable.js
- src/interactions/clickInteraction.ts
- src/interactions/doubleClickInteraction.ts
- src/reference.ts
- test/interactions/clickInteractionTests.ts
- test/testReference.ts
- test/tests.js
`Interaction.Click` responds to clicks within a component using a callback set through `onClick`
API-Breaks:
The `callback` setter on `Interaction.Click` has been reworked and renamed into an `onClick` getter/setter API.
Fixes #1684
> [ClickInteraction] - Refactor to new Interaction API

- plottable.d.ts
- plottable.js
- src/components/table.ts
- test/core/tableTests.ts
- test/tests.js
Closes #1714 
As per title. addComponent used to throw an error if the cell was already containing a component. Now it just appends the component to a group (and creates the group if necessary). Unit test included.
> [Table] - addComponent to already occupied cell appends component

- test/core/componentTests.ts
- test/tests.js
To reproduce 
http://localhost:9999/test/tests.html#
Fix: regex strip down of suffix.
> 2 tests were failing if the # symbol was presented in the URL

- plottable.d.ts
- plottable.js
- src/components/abstractComponent.ts
- src/components/componentGroup.ts
- test/core/componentGroupTests.ts
- test/mocks.ts
- test/testReference.ts
- test/testUtils.ts
- test/tests.js
This change causes `Component.Group` to behave as though it's not there by occupying the entirety of any space in the final offer, although it will still request no more space than is necessary to fit its `Components`.
Close #1791.
Also should not break #1255.
> Component.Group now occupies all offered space

- plottable.js
- src/components/interactive/dragBoxLayer.ts
- test/components/interactive/dragBoxLayerTests.ts
- test/tests.js
Previously, a `DragBoxLayer` whose box was dragged all the way to the edge would show a "resizing" cursor, even though the user's cursor might be outside the `DragBoxLayer` and hence unable to click on it. This is because the hover-sensitive area is larger than the box itself.
Resolved by using a clipPath to hide the parts of the drag-box that are outside the `DragBoxLayer`.
> Enable clipPath on DragBoxLayer.

- plottable.js
- src/components/axes/timeAxis.ts
- test/components/timeAxisTests.ts
- test/tests.js
Before (see URL) we were always setting the number of tiers to the maximum value (2). That meant that if we were only ever using 1 tier, there would be whitespace reserved for the second tier, which will never be used.
We now look through configurations and derive the maximum number of tiers.
Catch: If there is a chance to ever display 2 tiers, we will leave space for 2 tiers even when only 1 tier is displayed, because we don't want the graph to jump on resize of the axis
Also included small refactoring:
- added a private static default configurations _DEFAULT_TIME_AXIS_CONFIGURATIONS
All should help readability 
Before: http://jsfiddle.net/9kk194m6/2/
After: http://jsfiddle.net/6yvtwzvm/
> [timeAxis] Height computed from maximum number of tiers

- plottable.d.ts
- plottable.js
- src/components/plots/linePlot.ts
- test/components/plots/linePlotTests.ts
- test/tests.js
Brandon, a couple of questions: 
1. I've repeated code in linePlotTests.ts that could be shared once this merges with the Bar closest plot data work. See assertPlotDataEqual(). What are your thoughts on sharing this code? And where would you prefer to put it if we were to share?
2. There's also a block of code at the end of getClosestPlotData() that could be shared between the bar and line case. We can talk about that as well.
> First pass Line.getClosestPlotData() impl.

- plottable.js
- src/scales/colorScale.ts
- test/scales/scaleTests.ts
- test/tests.js
BLUF Creating a `<plottable_color_testing>` element is less likely to be background-colored by an external stylesheet
Added unit test. Testing the exact bug fix is not a good idea, since the bug itself freezes the entire browser. Instead UnitTest is testing if the CSS specified color is applied. By doing this we can test cross-browser solution of the fix.
Introduction: We are having an internal representation of all Components. The ColorScale knows the possible colors it can have. It does this by creating `<div>` elements and getting their color (such that CSS is also taken into account). 
Problem: Since the user can specify more than the `20` colors we use by default, the JS keeps creating `<div>`s until the divs don't have a color anymore. Also, the JS cannot read the CSS directly. Now, …
> [colorScale] Quickfix for infinite recursion bug on CSS colors

- plottable.d.ts
- plottable.js
- src/components/plots/barPlot.ts
- test/components/plots/barPlotTests.ts
- test/tests.js
Bar plots would normally place their pixelPoints for `getAllPlotData` at the top of the bar under the assumption that the bar was positive valued.  This is incorrect if the bar is negative-valued or has a different barAlignment
Bars should now place their pixelPoints at the bottom of the bar if they are negative-valued (left of the bar for horizontal bar plots)
Accompanying JSFiddle - http://jsfiddle.net/8w5v19ry/1/
> [BarPlot] - getAllPlotData pixelPoints corrected for negative-valued bars and barAlignment

- test/testUtils.ts
- test/tests.js
Util function checks if the browser is IE.  If it is, it uses the initWheelEvent workflow that only IE uses.
Fixes #1837
> [triggerFakeWheelEvent util] - Safari compatible

- plottable.d.ts
- plottable.js
- src/components/plots/abstractStackedPlot.ts
- src/utils/utils.ts
- test/components/plots/stackedBarPlotTests.ts
- test/components/plots/stackedPlotTests.ts
- test/tests.js
- test/utils/utilsTests.ts
Closes #1838
Before: http://jsfiddle.net/d2te4yct/
After: http://jsfiddle.net/d2te4yct/2/
Technical description: If the y-value of one of the data sets was not convertible to string for a given x-value, all subsequent bars that would stack on top of the broken bar for that x-value (for example in the fiddle the red bar is in air)
Exception thrown: `Error: Invalid value for <rect> attribute y="NaN"`
Solution: Default y-values to 0, when the string cannot be converted to the number
**Alternative approach**
Throw an exception when user presents such data. The difference is that the exception should be more meaningful. User most probably did not want to specify a non-convertible string for a numeric y-axis. @jtlan @bluong What do you think?
**Decision** : We do not want that behavior
> [abstractStackedPlot] stackedBar fail gracefully when presented with wrong data

- tslint.json
class-name enforces that our classes and interfaces are CamelCased
> [TSLint Rule] - setting class-name to true

- tslint.json
This disallows the usage of placing public/private into the parameters of the constructor.
Neat:
```typescript
constructor(foo: number) {}
```
Messy:
```typescript
constructor(private foo: number) {}
```
> [TSLint Rule] - adding no-constructor-vars rule

- src/components/plots/rectanglePlot.ts
- src/components/table.ts
- src/core/colors.ts
- src/core/domainer.ts
- src/scales/quantitativeScale.ts
- test/components/labelTests.ts
- test/components/legendTests.ts
- test/components/numericAxisTests.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/gridPlotTests.ts
- test/components/plots/plotTests.ts
- test/components/plots/stackedBarPlotTests.ts
- test/core/componentContainerTests.ts
- test/core/componentGroupTests.ts
- test/core/componentTests.ts
- test/drawers/drawerTests.ts
- test/interactions/hoverInteractionTests.ts
- test/scales/scaleTests.ts
- test/testUtils.ts
- test/utils/utilsTests.ts
- tslint.json
The rule disallows the usage of consecutive blank lines
Neat:
```typescript
var foo = "foo";
var bar = "bar;
```
Messy:
```typescript
var foo = "foo";
var bar = "bar";
```
> [TSLint Rule] - adding no-consecutive-blank-lines rule

- tslint.json
Disallowing having cases in a switch statement to fall into each other
Neat:
```typescript
switch(foo) {
case 1:
doStuff(foo);
break;
case 2:
doStuff2(foo);
}
```
Messy:
```typescript
switch(foo) {
case 1:
doStuff(foo);
case 2:
doStuff2(foo);
}
```
> [TSLint Rule] - adding no-switch-case-fall-through rule

- plottable.d.ts
- plottable.js
- src/components/axes/numericAxis.ts
- src/components/plots/barPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/scatterPlot.ts
- src/components/plots/stackedAreaPlot.ts
- src/components/plots/stackedBarPlot.ts
- src/scales/categoryScale.ts
- src/scales/colorScale.ts
- test/core/tableTests.ts
- test/tests.js
- tslint.json
This checks if there is a single space in a single line comment between the / and the comment itself
Neat:
```typescript
// Insert comment here
```
Messy:
```typescript
//Insert Comment here
```
> [TSLint Rule] - adding comment-format check-space rule

- plottable.d.ts
- plottable.js
- src/components/abstractComponent.ts
- src/components/abstractComponentContainer.ts
- src/components/table.ts
- test/core/componentGroupTests.ts
- test/core/componentTests.ts
- test/core/tableTests.ts
- test/tests.js
Changelog:
- No longer setting the parent field, but rather have a method for doing that, which also detaches the component from its old parent (if there's the case)
- No longer throwing an error if the component was already setup or anchored, as we can now do it
- Throwing an error if we are trying to add `null` to a table cell
Closes #1823 
Before: http://jsfiddle.net/0r93afbf/
After: http://jsfiddle.net/0r93afbf/5/
Fiddle explanation: Click on the button. If it works correctly, the label "AWESOME" should be taken from the x-Axis and put inside the graph. The default position is center (vertically and horizontally)
> [abstractComponentContainer] Can now merge groups that are already anchored

- plottable.d.ts
- plottable.js
- src/components/plots/abstractStackedPlot.ts
- src/components/plots/rectanglePlot.ts
- src/drawers/arcDrawer.ts
- src/drawers/rectDrawer.ts
- src/utils/utils.ts
- test/components/plots/piePlotTests.ts
- test/components/plots/rectanglePlotTests.ts
- test/components/plots/stackedAreaPlotTests.ts
- test/tests.js
- test/utils/utilsTests.ts
Closes #1848 #1850 #1851 
A couple of graphs, when presented with badly formatted data, were just exploding. We want to handle these cases more gracefully now. The ticket is about `Plot.StackedArea`, `Plot.Pie`, `Plot.Grid`
Plot.StackedArea
===
Before: http://jsfiddle.net/d2te4yct/10/
After: http://jsfiddle.net/d2te4yct/11/
Plot.Pie
===
Before: http://jsfiddle.net/vmzfzx88/3/
After: http://jsfiddle.net/vmzfzx88/4/
Plot.Grid
===
(difference here is more subtle, basically now nothing is thrown in the console)
Before: http://jsfiddle.net/wd1mmd38/
After: http://jsfiddle.net/wd1mmd38/1/
Added unit tests for each
Also, there is a discussion about `null` and `undefined` which should behave the same. That is a discussion for #1866
> [Plot] Graphs fail gracefully when presented with badly formatted data

- src/components/axes/abstractAxis.ts
- src/components/axes/categoryAxis.ts
- src/components/axes/numericAxis.ts
- src/components/axes/timeAxis.ts
- src/components/legend.ts
- src/components/plots/abstractXYPlot.ts
- src/drawers/areaDrawer.ts
- src/drawers/lineDrawer.ts
- src/scales/abstractScale.ts
- src/scales/interpolatedColorScale.ts
- src/scales/quantitativeScale.ts
- src/scales/tickGenerators.ts
- src/utils/utils.ts
- test/core/tableTests.ts
- tslint.json
`tslint.json` rule for `whitespace: check-branch` was previously broken. After reading this https://github.com/palantir/tslint/blob/master/docs/sample.tslint.json it seems like the first argument of the array has to be boolean true, which meant that the check-branch was not actually passed as an argument, but instead coerced the string to `true`. 
In this commit: fixed that, applied the changes through regex replace and rearranged the rules to be consistent with the suggested style
> [style] Whitespace rule enforced

- plottable.d.ts
- plottable.js
- src/components/abstractComponent.ts
- src/components/abstractComponentContainer.ts
- src/components/axes/abstractAxis.ts
- src/components/axes/categoryAxis.ts
- src/components/componentGroup.ts
- src/components/interpolatedColorLegend.ts
- src/components/label.ts
- src/components/legend.ts
- src/components/plots/barPlot.ts
- src/components/table.ts
- src/core/animator.ts
- src/scales/categoryScale.ts
- src/scales/interpolatedColorScale.ts
- src/scales/quantitativeScale.ts
- src/scales/tickGenerators.ts
- test/components/plots/plotTests.ts
- test/mocks.ts
- test/testUtils.ts
- test/tests.js
- tslint.json
We no longer have space before `:`. Also updated the tslint rules to enforce that
> Refactor colon whitespace

- src/animators/baseAnimator.ts
- src/components/axes/timeAxis.ts
- src/components/componentGroup.ts
- src/components/plots/abstractPlot.ts
- src/components/plots/clusteredBarPlot.ts
- src/core/dataset.ts
- src/scales/interpolatedColorScale.ts
- src/utils/domUtils.ts
- tslint.json
This rule checks to make sure there is whitespace in front of specified tokens that are specified via the one-line rule.
Example specified token: `{` after an if like `if (foo) {`
Messy:
```typescript
if (foo){
...
```
Neat:
```typescript
if (foo) {
...
```
> [TSLint Rule] - adding one-line check-whitespace rule

- plottable.d.ts
- plottable.js
- src/reference.ts
- src/utils/callbackSet.ts
- test/testReference.ts
- test/tests.js
- test/utils/callbackSetTests.ts
It's ... a set of callbacks. It can be used to implement direct-reference for callback registration, rather than the key model currently used on `Broadcaster`.
We can't use d3.set because it only accepts string keys.
[ES6 set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) isn't available yet, and we'd still have to extend it to enable calling the callbacks.
Hits the first checkbox on #1915.
> Implement CallbackSet.

- plottable.d.ts
- plottable.js
- src/utils/utils.ts
- test/tests.js
- test/utils/utilsTests.ts
Previously, a bad accessor-function or a weird input array would cause `undefined` to be returned. Since the entire point of `Utils.min()` and `Utils.max()` was to be safer than the d3 versions, they now return
the default value whenever `undefined` would be returned.
> Utils.min() and Utils.max() now return defaultValue in all bad cases.

- plottable.d.ts
- plottable.js
- src/components/component.ts
Moving from `if (alignment === "top") {` to become `if (alignment === Alignment.TOP) {`
Typescript does not have support for non-number based enums so this was an acceptable substitute that I found (http://stackoverflow.com/questions/15490560/create-an-enum-with-string-values-in-typescript)
> Replace string constants with static members of Alignment class

- plottable.js
- src/components/component.ts
- test/core/componentTests.ts
- test/tests.js
As before, to avoid accidentally mutating the internal origin.
> Component.origin() returned cloned point.

- plottable.d.ts
- plottable.js
- src/components/plots/barPlot.ts
- src/components/plots/clusteredBarPlot.ts
- src/components/plots/gridPlot.ts
- src/components/plots/plot.ts
- src/components/plots/stackedAreaPlot.ts
- src/components/plots/stackedBarPlot.ts
- src/components/plots/stackedPlot.ts
- src/components/plots/xyPlot.ts
- src/reference.ts
Based on discussions in #1966, we're using a parallel structure for attributes and properties.
Signature of `_Projection` should be changed to match `_AccessorScaleBinding` from #1966.
Also, added **d3.d.ts** to **reference.ts** so Typescript tooling can actually resolve D3 methods.
> Use a D3.Map for the attribute-projector bindings.

- plottable.d.ts
- plottable.js
- src/animators/rectAnimator.ts
- src/components/plots/barPlot.ts
- src/components/plots/clusteredBarPlot.ts
- src/components/plots/gridPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/plot.ts
- src/components/plots/rectanglePlot.ts
- src/components/plots/stackedAreaPlot.ts
- src/components/plots/stackedBarPlot.ts
- src/components/plots/stackedPlot.ts
- src/components/plots/xyPlot.ts
- src/core/interfaces.ts
- src/drawers/arcDrawer.ts
- src/drawers/drawer.ts
- src/utils/utils.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/plotTests.ts
- test/components/plots/scatterPlotTests.ts
- test/core/metadataTests.ts
- test/tests.js
More powerful than just passing the metadata, and it will be useful later when getting rid of `Dataset` keys.
> Pass Dataset to Accessors instead of metadata.

- plottable.d.ts
- plottable.js
- src/components/plots/piePlot.ts
- src/drawers/arcDrawer.ts
- test/drawers/arcDrawerTests.ts
- test/tests.js
Restoring _Drawers back to their previous state.  Utiliize generateAttrToProjector to stay as consistent with the current codebase as possible
> restructure piePlot to use old arcDrawer architecture

- plottable.d.ts
- plottable.js
- src/core/renderController.ts
- src/utils/set.ts
- test/tests.js
- test/utils/setTests.ts
>"The loop was kind of pointless."
@jtlan, a155f04
In fact, the loop was super critical, but because the logic was so convoluted, it was difficult to tell. New logic for `RenderController`'s `flush()`:
* Save off current `Set` of `Component`s that have requested a render.
* Create a new `Set` for `Component`s that request a render while we're drawing.
* Draw all `Component`s in the saved-off `Set`.
* If there are `Component`s that have requested a render while we were drawing, request another frame.
> Fix the logic in RenderController.

- plottable.js
- src/interactions/interaction.ts
- test/interactions/interactionTests.ts
- test/tests.js
Closes #2012
Calling `detachFrom` twice used to throw an error. Fixed the error and added comprehensive testing for the testcase. Waiting for a merge, then opening this up
Before 1: http://jsfiddle.net/zLerabxg/
After 1:http://jsfiddle.net/zLerabxg/2/
Before 2:http://jsfiddle.net/zLerabxg/1/
After 2: http://jsfiddle.net/zLerabxg/3/
> [Interaction] Interaction fix

- plottable.d.ts
- plottable.js
- src/components/plots/gridPlot.ts
- src/components/plots/plot.ts
- src/utils/utils.ts
- test/components/plots/areaPlotTests.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/gridPlotTests.ts
- test/components/plots/linePlotTests.ts
- test/components/plots/piePlotTests.ts
- test/components/plots/plotTests.ts
- test/components/plots/rectanglePlotTests.ts
- test/components/plots/scatterPlotTests.ts
- test/components/plots/stackedAreaPlotTests.ts
- test/components/plots/stackedBarPlotTests.ts
- test/scales/scaleTests.ts
- test/tests.js
- test/utils/utilsTests.ts
Quite a few things have happened but all has been discussed prior.
* `project()` has been renamed to `attr()` and will be referred as such for the remainder of the PR
* the value parameter to `attr()` will be assumed to be an `_Accessor` or a `number` or a `string` or the "domainType" if a scale is provided.  No more key strings.
* `attr()` has been given a rework similar to how the property endpoints have been reworked and thus has a getter, a setter without a scale, and a setter with a scale
Few things to note:
* `Utils.Methods.accessorize` has been removed
* The `colorScale` argument to `Plots.Grid` has been removed
> [Plot] - `project()` has now been named to `attr()`.  Completely reworked.

- plottable.d.ts
- plottable.js
- src/components/axes/timeAxis.ts
- src/scales/timeScale.ts
- src/utils/formatters.ts
- test/components/timeAxisTests.ts
- test/scales/timeScaleTests.ts
- test/tests.js
Instead we defined our own enum called TimeInterval, which we expose to the public API.
The reasoning behind this change is that we do not want d3 implementation details (internals) to leak out to the user.
> [timeAxis & timeScale] TimeAxis configurations no longer expose d3.time

- plottable.js
- src/core/renderController.ts
- src/utils/formatters.ts
Issue:  The try, catch block inside the `rendererController.flush()`. If anything inside here (and there's a lot in her) fails and throws an exception, the exception is going to be caught by https://github.com/palantir/plottable/blob/timeD3/src/core/renderController.ts#L95 and not thrown immediately. Also, the renderer is going to loop infinitely, as it keeps rescheduling the component to a render. Removed the rescheduling bit. 
Reasoning behind it: From a discussion with @jtlan , the render should be (and I hope is) a pure function (no side effect), hence it should not modify the model. Since it does not modify the model, nothing changes. Since nothing changes, the component render will fail forever.
> Repaired renderer

- plottable.d.ts
- src/components/table.ts
- test/core/tableTests.ts
Note the underscore in front.  We should probably not expose this type
> [Table] - Hiding _IterateLayoutResult type

- plottable.js
- src/core/renderController.ts
- test/core/renderControllerTests.ts
- test/testReference.ts
- test/tests.js
b98a94b687de50b87143e2e64a001b4b7e46d4b2 caused a problem by removing the declaration of a new `_componentsToRender` `Set` before the loop where all the `Components` were drawn. That change caused a bug because `Component`s that were enqueued by another `Component`'s `render()` call would never be redrawn.
Added a test to catch this bug.
> Repaired RenderController again

- plottable.d.ts
- plottable.js
- src/components/axes/axis.ts
- src/components/axes/categoryAxis.ts
- src/components/axes/numericAxis.ts
- src/components/axes/timeAxis.ts
- src/components/interpolatedColorLegend.ts
- src/components/label.ts
- test/components/baseAxisTests.ts
- test/components/categoryAxisTests.ts
- test/components/interpolatedColorLegendTests.ts
- test/components/labelTests.ts
- test/components/numericAxisTests.ts
- test/components/timeAxisTests.ts
- test/tests.js
The name `orient` sounds like it should be affecting state even though it falls under our convention of getters/setters with a noun name.  It should be renamed to `orientation`.
> orient -> orientation

- plottable.d.ts
- src/components/axes/axis.ts
- src/components/axes/categoryAxis.ts
- src/components/axes/numericAxis.ts
- src/components/axes/timeAxis.ts
Axes now have a generic type that reflects the domain type of the input scale.  This should not affect anyone who's using `Axis.Category` or `Axis.Numeric` and it helps us reason about our own code.
> [Axis] - Generics!

- plottable.d.ts
- plottable.js
- src/components/plots/areaPlot.ts
- src/components/plots/gridPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/piePlot.ts
- src/components/plots/plot.ts
- src/components/plots/rectanglePlot.ts
- src/components/plots/scatterPlot.ts
- src/components/plots/stackedAreaPlot.ts
- src/components/plots/stackedBarPlot.ts
- src/components/plots/stackedPlot.ts
- src/components/plots/xyPlot.ts
- src/core/dataset.ts
- src/core/interfaces.ts
- test/components/plots/gridPlotTests.ts
- test/components/plots/piePlotTests.ts
- test/components/plots/stackedAreaPlotTests.ts
- test/components/plots/stackedBarPlotTests.ts
- test/components/plots/stackedPlotTests.ts
- test/core/metadataTests.ts
* `_Accessor` is now exposed as `Accessor` and will be referred to as such
* `Accessor` now takes in a generic type param to signify the return type of the Accessor function
* `Plots.Pie` no longer requires a generic type as the types are applied to the specific property functions
> Generic accessor

- plottable.d.ts
- plottable.js
- src/components/plots/areaPlot.ts
- src/components/plots/barPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/piePlot.ts
- src/components/plots/rectanglePlot.ts
- src/components/plots/scatterPlot.ts
- src/components/plots/stackedAreaPlot.ts
Moving appropriate defaults from `generateAttrToProjector()` to the constructor so that appropriate getter calls to those attirbutes can be called safely.
> [Plot] - Default keys

- plottable.js
- src/components/plots/linePlot.ts
The "defined" attribute is already defined in `XYPlot` meaning that the code in `Plots.Line` here is redundant
> [Plots.Line] - Deleting reapplication of "defined" attribute

- Gruntfile.js
- package.json
Upgraded [`grunt-bump`](https://github.com/vojtajina/grunt-bump) to have access to prerelease versioning:
* Running `grunt-bump: premajor` when the current version is `0.54.0` will set the version to `1.0.0-rc.0`.
* Running `grunt-bump: prerelease` will then set the version to `1.0.0-rc.1`.
You will still have to run `grunt dist-compile` and `grunt gitcommit:version` to finish creating a release version.
> grunt-bump upgrade

- .travis.yml
Also removed the possibility of a livelock
Issue: 
By using the sauce connection, we were basically creating a tunnel which we were not using. Sauce Connection, as it is documented [here](https://docs.saucelabs.com/reference/sauce-connect/) , only needs this tunnel if the hosting environment is behind a firewall. Since this is an open source project and Travis is publicly accessible, there is no need for that.
Also, when we were running the tests, due to some misconfiguration (I believe in `Grunt`, we were not reusing the TLS tunnel, but instead creating a new insecure one. This basically meant that we were opening 2 tunnels per commit, one of which we were not using.
Future considerations:
When the push was a code review, it basically spawn 2 tasks (times 2 tunnels), which meant 4 …
> Reduced the build time to 3 minutes on travis

- plottable.d.ts
- plottable.js
- src/core/dataset.ts
- src/utils/map.ts
- test/tests.js
- test/utils/mapTests.ts
`keys()` and values() used to return `<any>`, which wasn't very helpful.
On a `Map<K, V>`, `keys()` now returns `K[]`, `values()` now returns `V[]`.
Also got rid of `Map.map()`, which besides being really goofy wasn't used anywhere.
> Improve typing on the map shim.

- .jshintrc
- Gruntfile.js
This should make it easier for us to configure our jshint settings similar to how we configure our tslint settings
> [JSHint] - extracting jshint configs to own file

- plottable.d.ts
- plottable.js
- src/components/plots/plot.ts
This function basically became redundant now that we have a nice `attr()` getter as well as appropriate property getters
> [Plot] - removing generateProjectors

- plottable.d.ts
- plottable.js
- src/components/plots/plot.ts
- src/scales/linearScale.ts
- src/scales/modifiedLogScale.ts
- src/scales/quantitativeScale.ts
- src/scales/scale.ts
- src/scales/timeScale.ts
- test/scales/modifiedLogScaleTests.ts
- test/scales/scaleTests.ts
- test/tests.js
Adding or removing an `ExtentsProvider` now causes the scale to `autoDomain()` if it's in automatic mode.
Made `_autoDomainIfAutomaticMode()` `protected`.
Made `_defaultExtent()` protected.
Addresses #2057, which I will close when this makes it to **develop**.
> Fixes to autodomain logic.

- plottable.d.ts
- plottable.js
- src/components/plots/areaPlot.ts
- src/components/plots/piePlot.ts
- src/components/plots/plot.ts
- src/components/plots/rectanglePlot.ts
- src/components/plots/xyPlot.ts
Found that in order to move the calculation from the `Drawer`s to the `Plot`s it would be significantly easier if each subclass were to just define the junk attributes themselves and then I can clean them up steadily in a much more obvious manner
> [Plot] - propertyToProjectors handled on a subclass basis

- plottable.d.ts
- plottable.js
- src/components/label.ts
- test/components/labelTests.ts
- test/components/numericAxisTests.ts
- test/tests.js
(Reverts 4aff28b80635da2f7ac1ab6b22db88e2d3474e00)
Basically, the syntactic sugar of being able to say
```Typescript
var title = new Plottable.Components.TitleLabel("My Title");
```
instead of
```Typescript
var title = new Plottable.Components.Label("My Title").classed(Plottable.Components.Label.TITLE_LABEL_CLASS, true);
```
> Bring back TitleLabel and AxisLabel

- plottable.d.ts
- plottable.js
- quicktests/overlaying/tests/animations/animate_horizontalBar.js
- quicktests/overlaying/tests/animations/animate_verticalBar.js
- quicktests/overlaying/tests/basic/basic_allPlots.js
- quicktests/overlaying/tests/basic/categoryAxis_timeAxis.js
- quicktests/overlaying/tests/basic/negative_stacked_bar.js
- quicktests/overlaying/tests/interactions/interaction_BarHover.js
- quicktests/overlaying/tests/realistic/rainfall_ClusteredBar.js
- quicktests/overlaying/tests/realistic/stocks.js
- src/components/plots/barPlot.ts
- src/components/plots/clusteredBarPlot.ts
- src/components/plots/stackedBarPlot.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/clusteredBarPlotTests.ts
- test/components/plots/stackedBarPlotTests.ts
- test/core/metadataTests.ts
- test/drawers/rectDrawerTests.ts
- test/tests.js
Reverts the "feature" added in #2075.
In particular, I don't find that it makes much sense to change the orientation of a `Plot.Bar` after construction. Doing so breaks both `x()` and `y()` property setters, as well as causes some major updating difficulties when setting up the scales to include the `baseline()` value.
> No longer allowed to change Bar Plot orientation after construction

- plottable.js
- src/components/plots/scatterPlot.ts
During the rework of Drawers and `_generateAttrToProjector()`, `Plots.Scatter` should be aligned with the idea that the projectors passed to the `Drawer`s are in fact the items that will be on the DOM node(s).
...And in doing so, I forgot to change the logic in the reset animation
QE: Animations were broken before for `Plots.Scatter`.  They should work now.
> [Plots.Scatter] - animation starts at an empty path

- plottable.d.ts
- plottable.js
- src/components/plots/piePlot.ts
- src/drawers/arcDrawer.ts
- test/components/plots/piePlotTests.ts
- test/tests.js
In accordance to #1913, the calculations for the attributes should not be done at the `Drawer` level but at the plot level.  I'm starting with `Plots.Pie` here
> [Plots.Pie] - All attribute calculations are done at the plot

- plottable.d.ts
- plottable.js
- src/core/renderController.ts
Decided not to remove the `RenderPolicy` type and instead just do some stringy enum cleanup in `RenderController.ts`
Fixes #2061
> [RenderController] Stringified policies

- plottable.js
- src/components/plots/areaPlot.ts
- src/components/plots/stackedAreaPlot.ts
- src/components/plots/stackedBarPlot.ts
It's already on `Plots.Area`.  Shouldn't need to be redeclared in `Plots.StackedArea`
> [Plots.StackedArea] - removing redundant class line

- plottable.js
- src/components/plots/linePlot.ts
- src/drawers/drawer.ts
- src/utils/utils.ts
- tslint.json
We should be using `Object.keys()` instead
> ban d3.keys

- plottable.d.ts
- plottable.js
- src/components/plots/barPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/rectanglePlot.ts
- src/components/plots/xyPlot.ts
- src/drawers/drawer.ts
- src/drawers/elementDrawer.ts
There was filtering done on the Drawer level.  This is now done on the appropriate `XYPlot` level.
> [Drawers.Element] - x/y/defined attributes removed

- plottable.d.ts
- src/components/plots/stackedAreaPlot.ts
- test/components/plots/stackedPlotTests.ts
- test/core/tableTests.ts
- test/tests.js
Closes #2003 #1921
Also fixed the signature of the `Plots.StackedArea.x()`, which was not consistent with the `Plots.Area.x()`
> Unskipped all tests 

- plottable.d.ts
- plottable.js
- src/components/plots/barPlot.ts
- src/components/plots/plot.ts
In `Plots.Bar`, the `<g>` containing the bars (`<rect>`s) used to carry the `bar-area` CSS class.
That class has been restored.
> Restore "bar-area" CSS class; rename _setupDatasetNodes() to _createNodesForDataset

- plottable.d.ts
- plottable.js
- src/components/plots/barPlot.ts
Closes #2208.
Well, this is one way of doing it. I did not really like the proper way, where 8 classes (scales) get polluted with a `getBaseValue` public method
**QE Notes**
Nothing should be affected. Tested overlaying tests and all works fine. Regression pass only. Bar Plots affected by this commit.
> [Plots.Bar] Fixed type for baselineValue()

- plottable.d.ts
- plottable.js
- quicktests/overlaying/tests/realistic/add_remove_dataset.js
- src/components/plots/areaPlot.ts
- test/components/plots/areaPlotTests.ts
- test/tests.js
The `Drawers.Line` wasn't being cleaned up when its associated `Dataset was` removed.
Added a test.
Added a quicktest.
> [Plots.Area] Fix regression: clean up line when removing datasets

- plottable.d.ts
- plottable.js
- quicktests/overlaying/tests/animations/animate_area.js
- quicktests/overlaying/tests/animations/animate_horizontalBar.js
- quicktests/overlaying/tests/animations/animate_line.js
- quicktests/overlaying/tests/animations/animate_scatter.js
- quicktests/overlaying/tests/animations/animate_verticalBar.js
- quicktests/overlaying/tests/basic/missing_stacked_area.js
- quicktests/overlaying/tests/basic/negative_stacked_bar.js
- quicktests/overlaying/tests/functional/base_animator.js
- quicktests/overlaying/tests/realistic/stocks.js
- src/components/plots/plot.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/plotTests.ts
- test/tests.js
Closes #2185
Also renamed it to `animated()`
**RFC** I prefer `willAnimate()`
> Plot.animate() should also function as a getter

- plottable.js
- src/scales/quantitativeScale.ts
- test/scales/linearScaleTests.ts
- test/scales/timeScaleTests.ts
- test/tests.js
`d3.extent()` behaves differently if the first element in the array isn't a `number`, so I filtered the values before passing them in.
Test fiddle showing the bug (on develop): http://jsfiddle.net/b48jk5yx/
One thing we should consider is if we want to have `Scales.Time` reject non-`Date` objects -- see the skipped test in **timeScaleTests.ts**.
One more thing to fix here is that `entities()` returns corrupted data if there are datums that are skipped. going to get to that next.
Test fiddle showing the bug (on `numericExtent`): http://jsfiddle.net/njqnu1vf/ (open the console)
> Fix extent calculation on QuantitativeScale to account for non-numbers.

- plottable.d.ts
- plottable.js
- quicktests/overlaying/tests/functional/base_animator.js
- src/animators/baseAnimator.ts
- src/components/plots/plot.ts
- src/drawers/drawer.ts
- test/drawers/drawerTests.ts
- test/tests.js
Closes #2197 
Separated the `draw()` method into 2 separate methods, one used for drawing, one used for retrieving the total draw time needed. 
Additions:
`Drawer.totalDrawTime()`
**BugFix:** The total drawing time on the animator was not computed correctly, as it was adding an extra step Delay
**QE Notes:**
In general nothing should have changed except:
- For a `Plots.Bar`, if we have labels on the bars (like in the `base_animator` overlaying test), the labels used to show up 1 interval later, which was not correct, now they show up correctly
- Added a new endpoint on the drawer called `totalDrawTime()`. For quick use case, this is copy+paste from the test I've written
```typescript
it("totalDrawTime()", () => {
var svg = TestMethods.generateSVG(300, 300);
var drawer = new …
```
> [Drawer] - the `draw()` endpoint should return this

- plottable.js
- src/components/plots/plot.ts
- test/components/plots/plotTests.ts
- test/tests.js
The secondary bug mentioned on #2236, remake of #2237.
Test fiddle showing the bug: http://jsfiddle.net/njqnu1vf/1/ (open the console)
**expected**: circles are drawn around the position of each `Entity`
**actual**: no circles drawn, error in console
Keep a different index that only counts the valid datums, and use that index to retrieve the `Selection`. Invalid datums are never drawn, so they have no `Selection`.
A better fix might be to have a method `selectionForDatum()` rather than `selectionForIndex()` on `Drawer`.
Fiddle as fixed on this branch: http://jsfiddle.net/ap0ujhu0/
> Use loopIndex when searching for selection.

- plottable.d.ts
- plottable.js
- src/components/axes/axis.ts
- src/components/axes/timeAxis.ts
- src/components/component.ts
- src/components/componentContainer.ts
- src/components/gridlines.ts
- src/components/interpolatedColorLegend.ts
- src/components/label.ts
- src/components/legend.ts
- src/components/plots/barPlot.ts
- src/components/plots/clusteredBarPlot.ts
- src/components/plots/plot.ts
- src/components/plots/stackedAreaPlot.ts
- src/components/selectionBoxLayer.ts
- src/core/symbolFactories.ts
- src/scales/quantitativeScale.ts
There are several instance variables that are protected that should be instead private.  Few cleanups that we would want to do before 1.0
QE: Regression pass please.  The JS got affected functionally in very small ways, specifically with how `Axis.Time` sets up its DOM elements and how `Plots.ClusteredBar` lays out the bars for the cluster, but these changes should hopefully not affect you.
> Privitizing

- plottable.d.ts
- plottable.js
- quicktests/overlaying/tests/basic/negative_stacked_bar.js
- quicktests/overlaying/tests/functional/base_animator.js
- src/components/plots/barPlot.ts
- test/components/plots/barPlotTests.ts
- test/tests.js
Being consistent since a parallel endpoint `labelsEnabled` is also plural
> [Plots.Bar] - labelFormatter -> labelsFormatter

- plottable.d.ts
- plottable.js
- src/components/legend.ts
- src/components/plots/plot.ts
- src/core/interfaces.ts
- test/testMethods.ts
- test/tests.js
`index` doesn't have a well-defined meaning for a general `Component`, so I've removed it from the base `Entity` type.
> Move index out of Entity into PlotEntity

- plottable.d.ts
- plottable.js
- src/components/component.ts
- src/components/plots/barPlot.ts
- src/components/plots/scatterPlot.ts
- src/core/renderPolicy.ts
- src/dispatchers/mouseDispatcher.ts
- src/dispatchers/touchDispatcher.ts
- src/utils/clientToSVGTranslator.ts
- src/utils/domUtils.ts
- test/components/labelTests.ts
- test/components/legendTests.ts
- test/components/selectionBoxLayerTests.ts
- test/core/componentTests.ts
- test/core/tableTests.ts
- test/tests.js
- test/utils/domUtilsTests.ts
Closes #2259
Changes:
- Things that can inferred (like return type of methods) are omitted now
- Style cleanup
- `getBBox` -> `elementBBox`
- `getParsedStyleValue` -> REMOVED (privatized)
- `isSelectionRemovedFromSVG` -> REMOVED
- `getElementWidth` -> `elementWidth`
- `getElementHeight` -> `elementHeight`
- `getSVGPixelWidth` -> REMOVED
- `getBoundingSVG` -> `boundingSVG`
- `getUniqueClipPathId` -> `generateUniqueClipPathId`
@bluong EDIT: second `getElementWidth` -> `getElementHeight`
**QE Notes** Regression pass
> Dom utils refactor

- plottable.d.ts
- plottable.js
- src/interactions/panZoomInteraction.ts
Doing this mainly so that we can answer the question for how to deal with this variable later.
The idea of PIXELS_PER_LINE is so the user has an understanding of the conversion for browsers like Firefox that report their wheel events differently than others.  This should in my opinion be configurable so that users can set it to a more correct value if they should so choose but currently as it is a static variable, it has the same on all plots which may or may not be correct.
What also is concerning is that I actually do not think that this belongs in `Interaction.PanZoom`.  It should instead be in something like `Interactions.Scroll` (which doesn't exist) or maybe even in `Dispatchers.Wheel`.
If we are certain that it should be a property of `Dispatchers.Wheel` then I can make it thus, …
> [Interaction.PanZoom] - privitizing PIXELS_PER_LINE

- plottable.d.ts
- plottable.js
- src/components/interpolatedColorLegend.ts
- test/components/interpolatedColorLegendTests.ts
- test/tests.js
API Breaks:
* `InterpolatedColorLegend` no longer takes in an `orientation` parameter + `formatter` parameter as arguments to the constructor
> [InterpolatedColorLegend] - removing optional arguments from the constructor

- plottable.d.ts
- plottable.js
- src/core/renderController.ts
- test/globalInitialization.ts
- test/tests.js
API Breaks:
* `RenderController._renderPolicy` is no longer exposed
* `RenderController.setRenderPolicy()` -> `RenderController.renderPolicy()`
QE: Regression pass should be enough.  You can try setting the renderPolicy if you're so curious, albeit I don't think you'll see much functional changes and mainly performance changes.
> [RenderController] - Adding getter/setter renderPolicy endpoint

- plottable.d.ts
- plottable.js
- src/components/axes/timeAxis.ts
- src/core/formatters.ts
- src/scales/timeScale.ts
The calculation is specific to `Axes.Time` and `Scales.Time`.  Since `Scales.Time` is more of the brains of the two, I thought that it should go on the `Scale` class
API Changes:
* `Formatters.timeIntervalTod3Time()` has been moved to `Scales.Time.timeIntervalTod3Time()`
> [Formatters] - moving intervalToTime function to the Scales.Time

- Gruntfile.js
- plottable.js
- quicktests/umd/app.js
- quicktests/umd/index.html
Avoids exporting `Plottable` to the global namespace if a module loader is used.
> Switch the template used for UMD.

- plottable.d.ts
- plottable.js
- quicktests/overlaying/tests/realistic/category_grid.js
- src/scales/interpolatedColorScale.ts
- src/scales/linearScale.ts
- src/scales/modifiedLogScale.ts
- src/scales/timeScale.ts
- test/components/plots/rectanglePlotTests.ts
- test/scales/scaleTests.ts
- test/tests.js
Closes #2271
Interpolated Color scale no longer takes the colorRange as a constructor argument. Instead, it is now set via the `range()` method
**Reason:** We want InterpolatedColor to be consistent with Color, which takes as a first argument the scale type. In the same time, the argument was optional, and could have been set by the `colorRange()` method
Changelog:
- `Scales.InterpolatedColor.colorRange()` -> `Scales.InterpolatedColor.range()`
- `new Scales.InterpolatedColor(colorRange, scaleType)` -> `new Scales.InterpolatedColor(scaleType)`
**QE Notes** Regression pass on interpolated color scale. Checked the overlaying tests myself
> Scale Refactor

- plottable.d.ts
- plottable.js
- quicktests/overlaying/tests/realistic/stocks.js
- quicktests/overlaying/tests/realistic/vertical_line.js
- src/components/plots/xyPlot.ts
- test/components/plots/barPlotTests.ts
- test/components/plots/stackedPlotTests.ts
- test/components/plots/xyPlotTests.ts
- test/tests.js
More accurately describes the functionality, and reduces confusion in the case of the getter:
```Javascript
plot.autorange(); // does this perform autoranging?
plot.autorangeMode(); // clearer
```
Also renamed the param to "autorangeMode".
> Rename autorange() to autorangeMode()

- plottable.js
- src/components/group.ts
- test/core/componentGroupTests.ts
- test/tests.js
The list of `Component`s in the implementation of `_forEach()` should be a shallow copy.
> Fix destroy() method on Group

- plottable.d.ts
- plottable.js
- src/components/axes/timeAxis.ts
- src/components/component.ts
- src/components/group.ts
- src/components/selectionBoxLayer.ts
New name better explains the purpose of the method and differentiates it from `requestedSpace()` and `computeLayout()`.
Close #2059.
> Rename _getSize() to _sizeFromOffer()

- plottable.d.ts
- plottable.js
- src/components/legend.ts
API Changes:
* `legend.symbolFactoryAccessor()` has been renamed to `legend.symbol()`
QE: Simple rename.  Should not need QE.
> [Legend] - rename symbolFactoryAccessor -> symbol

- plottable.d.ts
- plottable.js
- src/components/plots/barPlot.ts
- src/components/plots/linePlot.ts
- src/components/plots/plot.ts
- src/components/plots/scatterPlot.ts
We're currently consistent on trying to shorten our variable/function names where applicable (removing "get" / "set" / "is" in front where we can).  Since I think `_visibleOnPlot()` conveys the meaning of `_isVisibleOnPlot()` and it's more consistent with our vocabulary in our codebase, we should change the name.
API Changes:
* `plot._isVisibleOnPlot()` -> `plot._visibleOnPlot()`
QE: Protected function rename.  Should not require QE
> [Plot] - _isVisibleOnPlot -> _visibleOnPlot

- plottable.d.ts
- plottable.js
- src/utils/map.ts
- src/utils/set.ts
- test/tests.js
- test/utils/mapTests.ts
- test/utils/setTests.ts
As part of the API refactor, we introduced the ES6 shims for Map and Set. Also, we decided not to expose the d3 map/set anymore. The problem is that our Map and Set were not efficient.
However, Chrome and FF support ES6 Map / Set for quite a while, hence we can leverage their power and cut down O(n) to O(log n) / O(1).
[Browser Support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map):
```
Chrome: 38
Firefox: 25
IE: 11
Opera: 25
Safari: 7.1
```
For reference, [latest version](http://browsehappy.com/) of each browser at the time of writing is:
```
Chrome: 43
Firefox: 38
IE: 11
Opera: 30
Safari: 8
```
**Notice** The `size` field on the Set is no longer read-only. The reason for that is 25% time reduction (from 90-100 ms down to 15-25 ms) on the following …
> Map and Set performance improvements

- plottable.d.ts
- plottable.js
- src/plots/barPlot.ts
- src/utils/stackingUtils.ts
- test/plots/barPlotTests.ts
- test/tests.js
Closes https://github.com/palantir/plottable/issues/1284
Improved the call of `flush()` from `132 ms` down to `10 ms` by caching the result of `_getBarPixelWidth()`
Historic Before: http://jsfiddle.net/aycxz2ap/4/
Before: http://jsfiddle.net/aycxz2ap/1/
After: http://jsfiddle.net/aycxz2ap/3/
**QE Notes:** Bar Plot should behave the same. In particular the width of the bars should not behave weirdly. Also The main performance boost is in the PanZoom animation effect (as can be seen in the fiddle)
> Bar plot performance

- plottable.js
- src/components/table.ts
- test/plots/linePlotTests.ts
- test/plots/stackedPlotTests.ts
- test/tests.js
- tslint.json
Putting more enforcement through tslint.  The rule enforces that variables are either camelCased or UPPER_CASED.  Mainly to keep to a consistent style that Typescript variables are normally under the above heuristic.
Invalid:
```typescript
var one_two_three;
```
Valid:
```typescript
var oneTwoThree;
```
> [Tslint] - adding variable-name rule

- plottable.d.ts
- src/drawers/areaDrawer.ts
- src/drawers/drawer.ts
- src/drawers/lineDrawer.ts
`Selection<any>` is the correct return type, since there is data bound to the `Selection`. The error was initially discovered in #2349.
[NOQE] because there are no JS or CSS changes.
> Have selectionForIndex return d3.Selection<any>

- .eslintrc
- quicktests/color/main.js
- quicktests/overlaying/overlaying.js
- quicktests/overlaying/tests/functional/base_animator.js
- quicktests/overlaying/tests/realistic/animals.js
- quicktests/overlaying/tests/realistic/numeric_grid.js
- quicktests/overlaying/tests/realistic/rectangle.js
- quicktests/overlaying/tests/realistic/scatter_bar.js
- quicktests/overlaying/tests/realistic/symbols.js
- quicktests/quicktest.js
The rule enforces spacing around semicolons.  There can be no whitespace before and there must be some after.
Invalid:
```javascript
var foo = function (a) { return a ;};
```
Valid:
```javascript
var foo = function (a) { return a; };
```
> [ESLint] - applying default usage of semi-spacing

- .eslintrc
- Gruntfile.js
- quicktests/overlaying/overlaying.js
The rule disallows the usage of variables before they are defined
Invalid:
```javascript
function foo() {
doStuff(a);
}
```
Valid:
```javascript
function foo() {
var a = ...;
doStuff(a);
}
```
> [ESLint] - applying default usage of no-undef

- .eslintrc
- Gruntfile.js
- quicktests/color/main.js
- quicktests/overlaying/tests/animations/inflation.js
- quicktests/overlaying/tests/functional/padding.js
- quicktests/overlaying/tests/realistic/animals.js
- quicktests/overlaying/tests/realistic/phones.js
- quicktests/overlaying/tests/realistic/scatter_bar.js
- quicktests/umd/app.js
Rules disallows ending with trailing whitespace.
Using {\space} as a whitespace character.
Invalid:
```javascript
var foo = 3;{\space}{\space}{\space}
```
Valid:
```javascript
var foo = 3;
```
> [ESLint] - allowing for default usage of no-trailing-spaces

- .eslintrc
- quicktests/overlaying/tests/realistic/animals.js
- quicktests/overlaying/tests/realistic/numeric_grid.js
Tab characters in general should not be used.  Only spaces for alignment.
Using {\t} as a tab character
Invalid:
```javascript
{\t}{\t}var foo = "bar;
```
Valid:
```javascript
var foo = "bar";
```
> [ESLint] - applying default usage of no-mixed-spaces-and-tabs

- .eslintrc
- Gruntfile.js
- quicktests/color/main.js
- quicktests/overlaying/overlaying.js
- quicktests/overlaying/tests/realistic/animals.js
- quicktests/overlaying/tests/realistic/basic_pie_real.js
- quicktests/overlaying/tests/realistic/category_grid.js
- quicktests/overlaying/tests/realistic/scatter_bar.js
Default usage is where commas cannot be dangling at the end.
Invalid:
[ {foo: "bar"},
{foo: "baz"}, ]
Valid:
[ {foo: "bar"},
{foo: "baz"} ]
> [ESLint] - allowing for default usage of comma-dangle

- .eslintrc
- quicktests/color/main.js
- quicktests/overlaying/overlaying.js
- quicktests/overlaying/tests/animations/inflation.js
- quicktests/overlaying/tests/functional/categoryFormatter.js
- quicktests/overlaying/tests/functional/formatter.js
- quicktests/overlaying/tests/realistic/add_remove_dataset.js
- quicktests/overlaying/tests/realistic/cities.js
- quicktests/overlaying/tests/realistic/hockey.js
- quicktests/overlaying/tests/realistic/stocks.js
- quicktests/overlaying/tests/realistic/symbols.js
Rule by default forces spaces around operators.
Invalid:
```javascript
var a = 5+1;
```
Valid:
```javascript
var a = 5 + 1;
```
> [ESLint] - allowing for default usage of space-infix-op

- plottable.d.ts
- plottable.js
- src/interactions/panZoomInteraction.ts
- test/interactions/panZoomInteractionTests.ts
- test/tests.js
Allowing usage of `Interactions.PanZoom` on multiple scales.  Through the usage of either of the `addXScale()` / `addYScale()` / `xScales()` / `yScales()`, users can install multiple scales to use for the interaction.  In consequence, a panning or zooming will occur on all installed scales at once.
API Changes:
* `panZoomInteraction.addXScale()` has been added to add an x scale to the interaction.
* `panZoomInteraction.addYScale()` has been added to add a y scale to the interaction.
* `panZoomInteraction.removeXScale()` has been added to from an x scale from the interaction.
* `panZoomInteraction.removeYScale()` has been added to from an y scale from the interaction.
* `pandZoomInteraction.xScales()` has been added to get/set the x scales for the interaction.
* …
> [Interactions.PanZoom] - Usage on multiple scales

- test/tests.js
- test/utils/setTests.ts
Closes #2353
As [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/forEach) suggests, the second argument for the `forEach()` method is the same as the first argument. However, Safari is not following the spec, so had to add a HackHack for the test to pass.
> Safari test fix. ES6 Set forEach() badly implemented in Safari

- plottable.css
- plottable.d.ts
- plottable.js
- src/plots/piePlot.ts
- test/plots/piePlotTests.ts
- test/tests.js
Turns out that I can't use `arc.centroid()` directly here from d3, but I've implemented an identical technique as a substitute.
Fixes #1970 
Fiddle: http://jsfiddle.net/2z4pckh8/1/
> [Plots.Pie] Add labels to slices

- README.md
Stop linking to the Google group.
Direct people to our Gitter for help.
Link to tutorials no longer claims to link to the docs.
[NOQE] because no code changes, but @crmorford might want to take a look anyway.
> Clean up the readme.

- plottable.d.ts
- plottable.js
- src/interactions/interaction.ts
- test/interactions/interactionTests.ts
- test/tests.js
For temporarily disabling an `Interaction` without permanently disconnecting it from the `Component` it was attached to.
API:
```Typescript
/**
* Gets whether this Interaction is enabled.
*/
public enabled(): boolean;
/**
* Enables or disables this Interaction.
*/
public enabled(enabled: boolean): Interaction;
```
Example fiddle: http://jsfiddle.net/j0fnbmvr/
Open questions: Should interactive `Component`s (like `DragBoxLayer`) implement this functionality as well? Or is giving access to the internal `Interaction` sufficient?
Close #696.
> Add enable/disable functionality to Interaction

- .eslintrc
- quicktests/overlaying/tests/functional/titleLegend_change.js
Enforcing that variables can only be used after they have been declared / defined.  The configuration has been modified from the default to allow for usage of functions before they are declared.
Invalid:
```javascript
doStuff(foo);
var foo = 10;
```
Valid:
```javascript
var foo = 10;
doStuff(foo);
```
> [ESLint] - applying default usage of use-before-define

- .eslintrc
- quicktests/overlaying/tests/realistic/numeric_grid.js
This enforces spacing around keys and values in object literals.  By default, there is no space between the key and the ":" and there is a space between the ":" and the value.
Invalid:
```javascript
var a = { foo :"bar" };
```
Valid:
```javascript
var a = { foo: "bar" };
```
> [ESLint] - applying default usage of key-spacing

- .eslintrc
- Gruntfile.js
- quicktests/exampleUtil.js
- quicktests/overlaying/tests/animations/inflation.js
- quicktests/overlaying/tests/animations/inflationsegment.js
- quicktests/overlaying/tests/basic/basic_allPlots.js
- quicktests/overlaying/tests/functional/categoryFormatter.js
- quicktests/overlaying/tests/functional/formatter.js
- quicktests/overlaying/tests/realistic/hockey.js
- quicktests/overlaying/tests/realistic/phones.js
- quicktests/overlaying/tests/realistic/stocks.js
- quicktests/overlaying/tests/realistic/symbols.js
Enforces that variables are camelcased.  From my gatherings of Javascript, camelCasing variables is more conventional than underscore separation.
Invalid:
```javascript
var foo_bar = 5;
```
Valid:
```javascript
var fooBar = 5;
```
> [ESLint] - applying default usage of camelcase

- plottable.d.ts
- plottable.js
- quicktests/color/index.html
- src/plots/plot.ts
- src/plots/xyPlot.ts
Closes #2352
**Description**: If we are having a ScatterPlot with a lot of data points, every time we update the scale (which happens on every single pan or zoom), all the `DOM` elements corresponding to the points get modified (in particular translated). This is a costly operation and can be improved by translating the parent `<g>` and letting the drawing engine do the heavy lifting. 
**Problem1**: We cannot account nicely for scaling (when zooming) here. That is because the scale on the top element also modifies the size of the points (and that is not acceptable). Therefore, we ran for a compromise: Scale the points (i.e. zoom badly and lose resolution) during the zoom and recompute all the points after no more interaction exists.
**Problem2**: Because of Problem1, we no longer have the …
> PanZoom performance improvement

- plottable.js
- src/plots/stackedBarPlot.ts
- test/plots/stackedBarPlotTests.ts
`Plots.StackedBar` creates a function that computes the correct height, but wasn't previously returning that from `_generateAttrToProjector()`.
This change means that `Plots.StackedBar` will now work correctly with `Scales.ModifiedLog`.
Close #2304.
> [StackedBar] Computed height function is returned

- .eslintrc
- quicktests/overlaying/overlaying.js
Enforces that console statements are not used.  Especially for `console.log`, these statements are generally not helpful in production level code.  Albeit, they are useful at development level.  We can decide if we want to utilize this or not.
At the very least, we should probably use Plottable's warn so that we don't run into IE issues
> [ESLint] - applying default usage of no-console

- plottable.js
- src/axes/numericAxis.ts
- test/dispatchers/mouseDispatcherTests.ts
I was hoping I can get more stuff in this side branch, but this is literally just a QE review of https://github.com/palantir/plottable/pull/2424 .
Merging it into develop now so @PeterFaiman can get these changes as well.
QE Notes: 
- **Regression pass**: nothing should be changed
- **What has been modified**: The numeric axis had logic for wrapping tick labels, but that never happened anyway because the tick labels which were too big were just hidden.
- **Performance improvement**: Not big, but for 60 plots on a page the load time decreases `1700ms` -> `1100ms`
> Many plots perf improvement

- plottable.d.ts
- plottable.js
- src/core/formatters.ts
- src/scales/timeScale.ts
Also remove from non-deprecated src.
Fixes #2402
> Deprecate Plottable.MILLISECONDS_IN_ONE_DAY & Formatters.relativeDate()

- plottable.d.ts
- plottable.js
- src/scales/colorScale.ts
- test/scales/scaleTests.ts
Color._getPlottableColors() hits the DOM every time, which in turn
occurs every time a Color Scale is constructed. Adding a static cache
saves a few ms on every new Color().
> Cache the plottable colors on the Color Scale

- quicktests/overlaying/tests/animations/animate_line.js
Closes #2440
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse
> Fixed animate line data parsing issue in FF

- plottable.d.ts
- plottable.js
- src/components/dragBoxLayer.ts
- test/components/dragBoxLayerTests.ts
This simply passes through to the underlying interaction object.
Fixes #2386.
> add enabled() method for DragBoxLayer.

- .travis.yml
Adding `sudo: false` switches us over to Travis' container-based infrastructure, which should give us modest performance boosts in testing.
> Travis-CI improvements

- .gitignore
- Gruntfile.js
Part of #2445 
Refactored the Gruntfile even more as a followup of #2469 and part of my hack week project.
As part of this change:
- Improved incremental build time  | Before `9.127 s` | After `3.321 s`
- Typescript is creating a `.baseDir.ts` file. Added to gitignore. Known issue. https://github.com/grunt-ts/grunt-ts/issues/77
- Tests no longer get recompiled upon src changes. This will be caught in the travis CI, which makes sense to me.
This change has been briefly tested, but I want to see how it behaves in the wild. Ping @aicioara for any discovered issues. In particular, my addition `spawn: false` in the watch config was documented as unstable.
Not included in this change:
- The incremental build time can be improved even more by somehow caching the `tsc` command. Notice that `2 s` …
> Improved incremental build time of watch 

- Gruntfile.js
Before
After
Inspiration
https://github.com/gruntjs/grunt/issues/895
This is simply removing the `Running "foo:bar" task`, for watch only. The header is still used for all our CI stuff. 
Closes #2507
> [Grunt] No more noisy output from the concat pipeline

- package.json
I just noticed this, and decided to fix it because why not? Unless there is a reason this is not set already.
Currently npm install warns with the following message:
`npm WARN package.json plottable.js@1.4.0 No license field.`
Plottable is MIT licensed, according to the LICENSE file, and I don't like this warning message.
> Add a license field to package.json.

- plottable.d.ts
- plottable.js
- src/axes/numericAxis.ts
- test/axes/numericAxisTests.ts
Part of #2433
Approximating the width reduces measure() calls, which are expensive. Using a simple approximation speeds things up on my machine by 30% or more, depending on how many labels are measured to render the graph.
JSFiddle: http://jsfiddle.net/uk3b4ykj/1/
API Changes:
* `Plottable.Axes.Numeric.usesTextWidthApproximation(enable: boolean)` has been added as a getter/setter to enable approximation
This approximation is particularly suited to the Numeric axis, as numbers are all basically the same size in most fonts.
A test running 20 graphs takes between 400 and 500 ms to run.
With approximate text measuring, it takes between 250 and 350 ms.
This is definitely due to the measurement calls, as can be seen in the below timeline of a single graph render.
And the corresponding …
> Add a flag on Numeric axes to approximate the width of the labels.

- plottable.css
- plottable.d.ts
- plottable.js
- src/components/dragBoxLayer.ts
- test/components/dragBoxLayerTests.ts
- test/components/xDragBoxLayerTests.ts
- test/components/yDragBoxLayerTests.ts
- test/testMethods.ts
Added the ability to move drag boxes by clicking and dragging on the inside of the box. The functionality is accessed via the `movable()` API point on `DragBoxLayer`:
```Typescript
/**
* Gets whether or not the drag box is movable.
*/
movable(): boolean;
/**
* Sets whether or not the drag box is movable.
*
* @param {boolean} movable
* @return {DragBoxLayer} The calling DragBoxLayer.
*/
movable(movable: boolean): DragBoxLayer;
```
Example: http://jsfiddle.net/qr5t8754/
More complicated example: http://jsfiddle.net/657jg26g/
Close #365.
> Add movable() API point to DragBoxLayer

- plottable.d.ts
- plottable.js
- src/components/gridlines.ts
- test/components/gridlinesTests.ts
Currently, `Gridline`s are only able to render to our expectations when it is grouped with something like a `Plots.Scatter` or similar.  However, it would be nice if we could render these `Gridline`s by themselves without heavy reliance on a grouped component.
JSFiddle: http://jsfiddle.net/bluong63/z1pnmgL2/
Fixes #2532
> [Gridlines] - Allow to be rendered on its own

- test/scales/linearScaleTests.ts
- test/scales/modifiedLogScaleTests.ts
- test/scales/scaleTests.ts
- test/scales/tickGeneratorsTests.ts
- test/scales/timeScaleTests.ts
Fun thing to see is that I'm trying to move towards biasing towards a `const` usage over a `let` usage and as a result some test code is a bit more precise on what its testing.
> [TSLint] - enforce no-var-keyword on scaleTests

- plottable.d.ts
- plottable.js
- src/components/legend.ts
- test/components/legendTests.ts
Follow-up from PR #2461 and addresses issue #2434 
Currently there is no way to update the opacity of symbols in the legend in an API-endorsed way. This is desirable if you, for example, built a scatter plot of various datasets with varying colors and opacities, and would like the opacity in the legend to match.
This PR provides the following API endpoints on `Legend`:
```typescript
/**
* Gets the opacity of the symbols of the Legend.
*
* @returns {(datum: any, index: number) => number}
*/
symbolOpacity(): (datum: any, index: number) => number;
/**
* Sets the opacity of the symbols of the Legend.
*
* @param {number | ((datum: any, index: number) => number)} symbolOpacity
* @returns {Legend} The calling Legend
*/
symbolOpacity(symbolOpacity: number | ((datum: any, index: number) => …
```
> API endpoint to specify opacity of legend (take 2)

- plottable.d.ts
- plottable.js
- src/plots/scatterPlot.ts
- test/plots/scatterPlotTests.ts
Similar to how `Plots.Bar` has an `entitiesIn()` endpoint, `Plots.Scatter` can now use this endpoint to find all of the entities within the given range or with the given bounds.
API Changes:
```typescript
/**
* Gets the Entities that intersect the Bounds.
*
* @param {Bounds} bounds
* @returns {PlotEntity[]}
*/
entitiesIn(bounds: Bounds): PlotEntity[];
/**
* Gets the Entities that intersect the area defined by the ranges.
*
* @param {Range} xRange
* @param {Range} yRange
* @returns {PlotEntity[]}
*/
entitiesIn(xRange: Range, yRange: Range): PlotEntity[];
```
JSFiddle: http://jsfiddle.net/bluong63/o3s4wst5/
Closes #2519
> [Plots.Scatter] - Adding `entitiesIn()` endpoint

- plottable.js
- src/components/component.ts
- src/plots/xyPlot.ts
- test/components/componentTests.ts
- test/plots/xyPlotTests.ts
Closes #2538
Before: http://jsfiddle.net/ys358yxy/2/
After: http://jsfiddle.net/ys358yxy/1/
The issue was that an unanchored plot is not setting up the scale correctly (because it does not know how much space it has in the SVG) and we were not taking that into account. With this fix will only cache domains for anchored plots
Also as part of this PR: 
- Added tests for deferredRendering
- Fixed more issues caught by the tests and not observed through manual inspection
- `onDetachCallbacks` on the component are not called unless the component was already anchored
- added tests for the item above
- Rearranged the test file for XYPlot. I did not like that the beforeEach was doing way too much for the basic use cases of the XYPlot. Also, I did not like creating a new XYPlot category, so I …
> Deferred Rendering fix

- plottable.js
- src/components/label.ts
- test/components/labelTests.ts
fixes #2140 
Labels used to accept all types, now they will throw an error on any type that isn't a string.
> label.text() only accepts strings

- plottable.css
- test/components/componentTests.ts
Safari now correctly responds to `Click` and `Drag` `Interaction`s that start in the `<svg>`.
Close #2454.
---
Set the `pointer-events` property to "`visibleFill`". Default property is `"auto"`, which on `<svg>`s should behave the same as `"visiblePainted"`, which says:
>The element can only be the target of a mouse event when the visibility attribute is set to visible and when the mouse cursor is over the interior (i.e., 'fill') of the element and the fill attribute is set to a value other than none, or when the mouse cursor is over the perimeter (i.e., 'stroke') of the element and the stroke attribute is set to a value other than none.
However, on non-Safari browsers, `"auto"` appears to behave like `"all"`, whereas in Safari it appears to behave as `"none"`. `"visibleFill"` seems …
> Safari now correctly detects events in the SVG

- plottable.js
- src/components/component.ts
- test/components/componentTests.ts
- test/components/groupTests.ts
- test/components/tableTests.ts
`detach()` callbacks should be called whenever `detach()` is called, to make sure that the `Component` and its parent correctly disassociate.
The bug manifested when `detach()`-ing `Component`s that were in a `Group` or `Table` before the `Group` or `Table` was rendered.
> [HOTFIX] detach() callbacks should called even if not anchored()

- plottable.js
- src/components/dragBoxLayer.ts
- test/components/dragBoxLayerTests.ts
Because functional CSS properties (in this case `pointer-events`) were not being set directly on the elements, the resize cursors weren't showing.
On this branch: http://jsfiddle.net/5tw5efp9/
On **`develop`**: http://jsfiddle.net/36euzLjv/
> Apply the correct pointer-events styles on DragBoxLayer edges/corners.

- plottable.js
- src/interactions/keyInteraction.ts
- test/interactions/keyInteractionTests.ts
- test/testMethods.ts
closes #2499 
demo: http://jsfiddle.net/sqa7dw6c/4/
EDIT: talked offline; since there's a use case requiring the functionality, will fix the auto-repeating behavior.  Will add ```onKeydown```/revise ```OnKeyPress``` if there's new feature requests
> trigger keypress callback only once when the key was pressed

- plottable.js
- src/components/dragBoxLayer.ts
- src/components/xDragBoxLayer.ts
- src/components/yDragBoxLayer.ts
- test/components/dragBoxLayerTests.ts
- test/components/xDragBoxLayerTests.ts
- test/components/yDragBoxLayerTests.ts
The CSS classes for resizing (`x-resizable`, `y-resizable`, `movable`) are no longer applied if the `DragBoxLayer` is disabled.
With the fix: http://jsfiddle.net/uhpevd7n/1/
On **`develop`**: http://jsfiddle.net/uhpevd7n/
Closes #2542.
> DragBoxLayer doesn't show resize/move cursors if not enabled.

- plottable.css
- plottable.d.ts
- plottable.js
- src/components/guideLineLayer.ts
- src/reference.ts
- test/components/guideLineLayerTests.ts
- test/testMethods.ts
- test/testReference.ts
Added new class `GuideLineLayer`. This `Component` fully-occupies a cell in a `Table` (like `SelectionBoxLayer`), and draws either a vertical or horizontal line at a specified position in data- or pixel-space:
`DragLineLayer` will extend this class. This PR serves as step one towards #1640.
The class is generic on the type of value it would take in data-space:
```Typescript
class GuideLineLayer<D> extends Component {
...
}
```
`D` would be `number` if the `value()` of the line is a `number`, for example; it should also match the type of input to the `QuantitativeScale` used with the `GuideLineLayer`. `void` should be used if the `GuideLineLayer` is only used in pixel-space.
Features the following API points:
```Typescript
constructor(orientation: string); // "vertical" or "horizontal"
/** …
```
> Add GuideLineLayer

- plottable.js
- src/axes/timeAxis.ts
- test/axes/timeAxisTests.ts
`Axes.Time` now appropriately includes the margin in its space usage.
This means that if `Axes.Time` is given enough space to include the tiers as well as the margin, the margin is included in the height for the axis.
Fixes #2042
> [Axes.Time] - includes the margin in its height

- plottable.d.ts
- plottable.js
- src/plots/areaPlot.ts
- src/plots/barPlot.ts
- src/plots/piePlot.ts
- src/plots/plot.ts
- test/plots/piePlotTests.ts
- test/plots/plotTests.ts
Part of #2418 
Suggested improvements will come as separate PRs
150 Datasets (as requested) - Speedup `100x`
Before: http://jsfiddle.net/cn9x2p5j/2/ - `3300 ms`
After: http://jsfiddle.net/cn9x2p5j/3/ - `36 ms`
Affected (perf wise):
- Plot.datasets(). This method should be preferred for multiple datasets additions
Unaffected (perf wise):
- Plot.addDataset()
- Plot.removeDataset()
QE notes - affected points:
- Plot.datasets()
- Plot.destroy()
- Plot.addDataset()
- Plot.removeDataset()
QE notes - regression: 
- Everything should behave exactly the same
QE notes - performance: 
- Plot.datasets() should be 100x faster.
- Plot.destroy() should be faster
- Everything else should be exactly the same
> The batch datasets setter dispatches updates at the end in batch

- test/plots/segmentPlotTests.ts
Part of #2636
I will be doing multiple passes because I will get more context (and better sense of best practices) by refactoring other files. However, please flag anything that seems unusual.
- Added `afterEach()` to save some LOCs
> Refactor segment plot tests

- test/components/dragBoxLayerTests.ts
Part of #2623 
I will be doing multiple passes because I will get more context (and better sense of best practices) by refactoring other files. However, please flag anything that seems unusual.
- Added `afterEach()` to save some LOCs
[NOQE] as no JS changes
> Refactor drag box layer tests - Part 1

- test/components/guideLineLayerTests.ts
> Refactor guide line layer - Pass 1

- test/scales/categoryScaleTests.ts
- test/scales/scaleTests.ts
- test/testReference.ts
> Refactor Category Scale Tests - Pass 1

- test/components/xDragBoxLayerTests.ts
- test/components/yDragBoxLayerTests.ts
> Refactor x/y drag box layer tests - Pass 1

- test/components/selectionBoxLayerTests.ts
> Refactor selection box layer - Pass 1

- test/scales/interpolatedColorScaleTests.ts
- test/scales/scaleTests.ts
- test/testMethods.ts
- test/testReference.ts
> Refactor interpolated color scale tests - Pass 1

- bower.json
As per "Link to bundled definitions" explained at https://github.com/DefinitelyTyped/tsd#link-to-bundled-definitions
> Link to definitions in bower.json

- test/scales/linearScaleTests.ts
Part of #2640 
- Removed annoying console warnings
> Refactor linear scale tests - Pass 1

- test/scales/tickGeneratorsTests.ts
> Refactor tick generator tests - Pass 1

- plottable.d.ts
- plottable.js
- src/plots/wheelPlot.ts
- src/reference.ts
- src/utils/mathUtils.ts
- test/plots/wheelPlotTests.ts
- test/testMethods.ts
- test/testReference.ts
part of #2612  (broke the task down to 4 steps)
demo:
http://jsfiddle.net/ztsai/71xu10uz/10/
http://jsfiddle.net/ztsai/597x450n/2/
http://jsfiddle.net/ztsai/tfsLo1y3/2/
A sector is defined by `t`, `t2`, `r`, and `r2`:
```t<T>(startAngle?: number | Accessor<number> | T | Accessor<T>, scale?: QuantitativeScale<T>)```
```t2<T>(endAngle?: number | Accessor<number> | T | Accessor<T>)```
```r<R>(innerRadius?: number | Accessor<number> | R | Accessor<R>, scale?: QuantitativeScale<R>)```
```r2<R>(outerRadius?: number | Accessor<number> | R | Accessor<R>)```
original PR: https://github.com/palantir/plottable/pull/2672
> add wheel plot

- test/interactions/clickInteractionTests.ts
> Refactor click interaction tests - Pass 1

- test/interactions/doubleClickInteractionTests.ts
> Refactor double click interaction tests - Pass 1

- test/interactions/dragInteractionTests.ts
> Refactor drag interaction tests - Pass 1

- Gruntfile.js
This is to account for the tests being slow on iPad. Increased the upper bound from 3 min to 5 min. 
Settings taken from here https://github.com/axemclion/grunt-saucelabs
I also played around with other environments taken from here https://docs.saucelabs.com/reference/platforms-configurator/ . It seems like all of them need between 2:03 and 3:00 + to run all the tests so a higher upper bound make sense.
The reason why we did not have this issue before was less tests. Right now the tests need 60% more time compared to what we had when we released `1.0.0`, due to new features.
> Higher retry rate for saucelabs

- plottable.d.ts
- plottable.js
- src/components/interpolatedColorLegend.ts
- test/components/interpolatedColorLegendTests.ts
closes #1568
demo: http://jsfiddle.net/ztsai/mwowegms/11
```expands(expands?: boolean)``` gets/sets whether the legend will expand in the long direction
if `expands` is set to `true` then the legend would span either the width or height depending on the orientation
> allow InterpolatedColorLegend to span entire space

- test/scales/scaleTests.ts
- test/scales/timeScaleTests.ts
Part of #2640 
Skipped tests will be solved as part of 
- https://github.com/palantir/plottable/issues/2705
- https://github.com/palantir/plottable/issues/2689
> Refactor time scale tests - Pass 1

- plottable.d.ts
- plottable.js
- src/components/legend.ts
- src/core/config.ts
- test/components/legendTests.ts
This pull request allows specifying whether to create title elements on a Legend component.
It addresses an issue where the title element appears when hovering over the chart area on safari (http://jsfiddle.net/alyssa/q319g8ww). Was traced by @jtlan as an [open bug on safari](https://bugs.webkit.org/show_bug.cgi?id=139690).
Pull request also removes a line where 2 title elements were created per legend entry (screenshot below).
> Setting to add title elements to Plottable's legend

- plottable.js
- src/axes/timeAxis.ts
- test/axes/timeAxisTests.ts
`Axis.Time` has a bug where if annotations are enabled, then the axis would not allocate the space required for those annotations, resulting in a few weird bugs where margin is forced in order to show annotations but then the margin also appears, leaving the Axis in a mess...
> timeAxis size now includes annotation space

- test/core/renderControllerTests.ts
- test/testMethods.ts
Mostly addition of non-existent tests.
Note that it is infeasible to test RenderPolicies since that would require very precise timing, which could itself be troublesome but it would also require a timeout in our tests.  Timeouts in our tests can be bad since test runners can take excruciatingly long if those tests fail.
Closes #2639
> [RenderControllerTests] - revamping

- plottable.js
- src/plots/barPlot.ts
- src/scales/quantitativeScale.ts
- test/plots/barPlotTests.ts
Closes #2704
The issue is the following. 
When calculating the extent for a scale that backs up the major scale of a bar plot, that scale needs to take into account the width of the bars. This is done in pixel space to account for log scales. Now, the issue is sometime the scales are having inverted domain (most common scenario, all yScales have the lowest number in the domain corresponding to the highest number in pixel such that the origin is bottom - left).
Solved this in the most generic / readable possible way.
**QE:** Please let me know if more information is required. I should not have changed anything except auto domain calculation code for bar plot (and clustered bar and stacked bar) 
Fiddle tagged on this.
Before: http://jsfiddle.net/o3rzuqur/5/
After: …
> Horizontal bar plots no longer autoDomain wrongly

- plottable.d.ts
- plottable.js
- src/axes/axis.ts
- src/core/formatters.ts
- src/plots/barPlot.ts
- src/plots/plot.ts
- src/plots/scatterPlot.ts
Closes #2750
- Added better deprecated documentation for deprecated methods
- Synced the versioning number between existing comments and the `deprecate()` method
- Added missing deprecation messages
> Deprecation documentation in JSDocs

- plottable.js
- src/plots/barPlot.ts
- test/plots/barPlotTests.ts
**Issue**
In the horizontal bar plot, a label should be hidden if the bounding box is inside the chart area. The issue is sometimes a label is visible when there's space to show it while sometime it is partially cut off in y. 
**Fix**
The `labelPosition.y` is not set correctly in the `_drawLabel` function. I add one line to set  `labelPosition.y` to the center of the bar.
**JSFiddle**
*Case1*: 
Before: http://jsfiddle.net/ejzaqdcq/
After: http://jsfiddle.net/pnqm5hrb/1/
*Case2*:
Before: http://jsfiddle.net/ejzaqdcq/1/
After:http://jsfiddle.net/54rf5to1/1/
Close #2658.
> Horizontal Bar Plot hides labels that are partially cut off in y

- plottable.css
- test/components/componentTests.ts
**Issue** 
When there are several components in a group, the cursor style only show on the top component.
**Fix**
This issue happens because the `background-fill` in the `background` of the top component is blocking the `pointer-events` to lower components. I fix this by adding `pointer-events:none` to `background-fill` elements in css.
There still might be problems that `content` instead of `background`  is blocking the pointer-events, i.e. if we put a `label` on top of a `dragLineLayer`, the cursor style of `dragLineLayer` will not show correctly. But this is beyond the scope of this issue.
**JSFiddle**
A component is in front of the dragLineLayer.
Before:http://jsfiddle.net/7Lxzacoz/
After:http://jsfiddle.net/tm2oot96/1/
close #2647
> change the background-fill pointer-events

- test/dispatchers/keyDispatcherTests.ts
> Refactor key dispatcher tests - Pass 1

- plottable.d.ts
- plottable.js
- src/components/xDragBoxLayer.ts
- src/components/yDragBoxLayer.ts
- test/components/xDragBoxLayerTests.ts
- test/components/yDragBoxLayerTests.ts
Having the getters on a class error can be incredibly disruptive, and so this pull request seeks to remove these from the appropriate getters.  This is disruptive since the variables in association with the getters are private, which means that if one just wants to query if the variable exists, then javascript would error.
This is highly relevant on classes like `SelectionBoxLayer`, which depending on the situation might want to query the `xScale()` or `yScale()` and then operate on it if it is not null.
Closes #2734
> [SelectionBoxLayer] - remove errors on getters

- plottable.d.ts
- plottable.js
- src/core/formatters.ts
**Issue**
The argument `precision` in `Formatter.siSuffix` and `Formatter.general` is not clear.
**Fix** 
In `siSuffix`, `precision` is change to `maxNumberOfDecimalPlaces`
In `general`, `precision` is change to `numberOfSignificantFigures`.
close #2594
> Change name of arguments in siSuffix and general function in Formatter

- plottable.d.ts
- plottable.js
- src/components/dragBoxLayer.ts
- test/components/dragBoxLayerTests.ts
closes #2553 
detach all dragInteractions on a DragBoxLayer when it's destroyed or detached
destroyed:
original: http://jsfiddle.net/fee6p9w0/6/
fixed: http://jsfiddle.net/fee6p9w0/16/
note that after clicking destroy button, there's still console log indicating interaction callback being fired in the original fiddle when drag events happen.
detached:
original: http://jsfiddle.net/fee6p9w0/24/
fixed: http://jsfiddle.net/fee6p9w0/25/
after clicking `detach` button there shouldn't be any console log while dragging, clicking `attach` will bring interaction and dbl back.
> detach DragInteraction on DragBoxLayer.destroy()

- plottable.js
- src/axes/axis.ts
- test/axes/baseAxisTests.ts
**Issue**
`annotationTierCount()` will not reject negative values and a negative annotation tier count will result in negative height. 
**Fix**
In `annotationTierCount(annotationTierCount:number)`, if `annotationTierCount` is negative, throw an error.
**JSFiddle**
Before: https://jsfiddle.net/nup2ya6w/6/
After: https://jsfiddle.net/drq123db/1/
Close #2730
> throw an error with invalid annotation tier count

- plottable.js
- src/components/component.ts
- src/components/selectionBoxLayer.ts
- src/plots/plot.ts
- test/components/componentTests.ts
- test/components/dragBoxLayerTests.ts
- test/mocks.ts
- test/plots/plotTests.ts
Previously, if the URL changed without reloading the page, any `Component` that was re-anchored would lose its reference to its `clipPath`, because Plottable uses an absolute reference to the `clipPath` (due to https://github.com/palantir/plottable/pull/865). Now, `Component`s with `clipPath`s will update their references on rendering.
Before: http://jsfiddle.net/mpqwxg4n/7/
After: http://jsfiddle.net/4mrzogsp/
**NOTE**: For some reason, the bug currently only manifests on Firefox, even though less than 24 hours ago I saw it on Chrome too...
Close #2733.
> clipPath now updates on render

- plottable.js
- src/plots/plot.ts
- src/plots/xyPlot.ts
- test/plots/plotTests.ts
- test/plots/xyPlotTests.ts
fix auto-domaining of scale on bind for Plots.Plot
auto-range scale on set for Plots.XYPlot
#2396
before: http://jsfiddle.net/x7x05L4k/
after: http://jsfiddle.net/x7x05L4k/1/
> Updating scale should auto domain

- plottable.js
- test/dispatchers/touchDispatcherTests.ts
Part of #2628
One of the tests fails. Opened https://github.com/palantir/plottable/issues/2789
> Refactor touch dispatcher tests - Pass 1

- package.json
- plottable.js
- test/components/legendTests.ts
Typescript has recently released its 1.6 version: http://blogs.msdn.com/b/typescript/archive/2015/09/16/announcing-typescript-1-6.aspx.  We should upgrade our compiler so we can freely take advantage of the language's new features.
A few new features that we could be excited about:
* Class expressions (Very adhoc class creation that "may" be useful for testing)
* User defined type guards (A customizable way to type-guard variables, which can help us a ton on input validation)
* Abstract classes (Something that I think we wanted for about a year and can help us a ton in areas where we throw errors when a function is not defined (Note that this could lead us into an API break))
* Generic type aliases (There is a HACKHACK surrounding this that we can now resolve)
QE: This is a version bump …
> [Typescript] - Upgrading to 1.6

- plottable.js
- src/components/dragBoxLayer.ts
- src/components/selectionBoxLayer.ts
- test/components/dragBoxLayerTests.ts
- test/components/selectionBoxLayerTests.ts
Closes #2769
Add clip path behavior to the selectionBoxLayer as well as add tests for this new behavior. Now when using the selectionBoxLayer, you can no longer drag the selection and have it appear outside the chart; instead it will get clipped.
> Add clipPath to selectionBoxLayer

- plottable.d.ts
- plottable.js
- src/components/interpolatedColorLegend.ts
- src/components/legend.ts
- test/components/legendTests.ts
**Feature**
Display a different name on an ordinary Legend than the values in the colorScale domain using customized `Formatter`.`Formatter` is defined as `(d:any) => string`
```typescript
class Legend{
/**
* Gets the Formatter for the text.
*/
formatter(): Formatter;
/**
* Sets the Formatter for the text.
*
* @param {Formatter} formatter
* @returns {Legend} The calling Legend.
*/
formatter(formatter: Formatter): Legend;
}
```
Using  `formatter` will affect the behavior of `comparator`. We decide to make `comparator` work on formatted texts.
**JSFiddle**
Before:http://jsfiddle.net/yunhaolucky/cmf3ut7g/4/
After:http://jsfiddle.net/yunhaolucky/cmf3ut7g/3/
close #2125
> Support Formatter on Legend

- plottable.js
- src/scales/timeScale.ts
- test/scales/timeScaleTests.ts
Previously, the default extent was supposed to be based on the current day, but wound up defaulting instead to `[Unix epoch, + 1 second]`. The default extent has now been changed to be `[Unix epoch, + 1 day]`.
Close #2740.
> [Scales.Time] Change default extent to be wider and consistent.

- plottable.js
- src/axes/timeAxis.ts
- test/axes/timeAxisTests.ts
**Issue**
Previously in a TimeAxis, when its `tierLabelPosition` is set to "center", the end tick marks on two sides have different lengths. The first end tick mark's length is the height of the tier.
**Fix**
Now the lengths of the end tick marks are `axis.endTickLength()`, whose default value is 5.
**JSFiddle**
Before:http://jsfiddle.net/yunhaolucky/o87wsq9h/5/
After:http://jsfiddle.net/yunhaolucky/o87wsq9h/6/
close #2800
> correct end tick marks length when tier label positions are set to "center"

- plottable.d.ts
- plottable.js
- src/plots/barPlot.ts
- test/plots/barPlotTests.ts
**Issue** 
`entity.position` are used to calculate the nearest entity. It should return the data point calculated by scales (for stackedBarPlot, it should return data point plus offset). Previously, it returns wrong points when scale domain are reversed or bar datum values are negative. Also, `barPlot._pixelPoint()` should return the same result as `entity.position`.
**Fix** 
I change `barPlot._pixelPoint()` function and calculated `pixelPoint()` separately when the datum value is negative. Also, I also call`barPlot._pixelPoint()` inside `entity.position` to make them return the same point.
This fix should work in barPlot, stackedBarPlot and clusteredBarPlot.
**JSFiddle**:
`barPlot._pixelPoint()` vs `entity.position`
Before: http://jsfiddle.net/8gxszz87/1/
After: …
> Barplot's pixelpoint return data point

- plottable.d.ts
- plottable.js
- src/plots/linePlot.ts
- test/plots/linePlotTests.ts
Part of #2523 
Performance request from Contour.
Affects:
- Line Plot
- Area Plot
- Stacked Area Plot
New API points
- `Plots.Line`
```typescript
/**
* Gets the croppedRendering preformance option state.
*
* When croppedRendering option is enabled, lines that will not be visible in the viewport will not be
* drawn anymore (will not have corresponding SVG nodes). If only part of the data is in the viewport,
* then this option will boost of rendering. However, if all the data is rendered anyway, having this
* option enabled will cause a small overhead that can be noticed in the total render time.
*/
public croppedRenderingEnabled(): boolean;
/**
* Sets the croppedRendering performance option.
*/
public croppedRenderingEnabled(croppedRendering: boolean): Plots.Line<X>;
```
Demo:
- …
> Cropped Rendering Performance Option

- plottable.js
- src/plots/linePlot.ts
- test/plots/areaPlotTests.ts
- test/plots/linePlotTests.ts
Having this be on by default.
Tests change because having an array go through a map does not return the same reference, but `assert.include` uses reference checking I believe -___-
> [Plots.Line] - croppedRendering by default

- Gruntfile.js
- plottable.d.ts
We used to have code to hide the private members in the "plottable.d.ts" file.  After discussion and this thread here https://github.com/Microsoft/TypeScript/issues/1532 (tl;dr private members prevent incorrect subclass overrides), it seems it is not preferable for us to actively remove the private members as such.
> [plottable.d.ts] - Add back private members

- plottable.js
- src/components/legend.ts
- test/components/legendTests.ts
**Issue**: the order of entries in a Legend are different from its order in domains.
**Fix**: The previous comparator assumes all elements are equal, which cause problems when using different sorting methods. The new default comparator sorts the  formatted texts based on their corresponding indexes of domain names.
Before:https://jsfiddle.net/5pzsk1nv/
After:https://jsfiddle.net/yunhaolucky/5pzsk1nv/2/
This fix might not work if several entries have the same formatted text.
close #2839
> change the default comparator of legend

- test/axes/numericAxisTests.ts
This test is the only test in the current test suite that fails when executed under grunt in Visual Studio 2015. Resolved by changing "closeTo" value from 1 to 1.5
> tweak test for Windows

- plottable.js
- src/plots/barPlot.ts
- test/plots/barPlotTests.ts
The extents on a bar plot are based on the width of the bars.  As a result, if the barPixelWidth were to update, the extents have to update as well
> [Plots.Bar] - extents updated when barpixelwidth is updated

- plottable.d.ts
- plottable.js
- src/components/table.ts
- test/components/tableTests.ts
New API Point:
```Typescript
/**
* Returns the Component at the specified row and column index.
*
* @param {number} rowIndex
* @param {number} columnIndex
* @returns {Component} The Component at the specified position, or null if no Component is there.
*/
componentAt(rowIndex: number, columnIndex: number): Component;
```
Fiddle: http://jsfiddle.net/pbotk0v8/
Close #2842.
> [Table] Add method to return Component at a specified row, column index.

- test/utils/windowUtilsTests.ts
Was supposed to be [a testing review for `Configs`](https://github.com/palantir/plottable/issues/2627), but it turns out that `ADD_TITLE_ELEMENTS` is tested in `Legend` and `InterpolatedColorLegend`, where it's used. If we wind up adding `<title>` tags anywhere else, we should add tests for it there too.
This leaves `SHOW_WARNINGS`, for which I have added tests in this pull request.
Close #2627.
> [Testing audit] Configs / Utils.Window

- Gruntfile.js
Looking at our tool's [configuration options](https://github.com/axemclion/grunt-saucelabs#usage), it seems that we can update a few of the options to deal with the flakiness that has been happening lately.
2 of the options have been removed since they did not seem to do anything.
1 option has been added ("maxRetries") which should hopefully decrease our chances of SauceLabs flaking out on us.  "maxRetries" sets how many times a test will run if the test reaches a timeout error, which sounds like an option that is designed for flaky builds.  This setting will be set to 5.  I do admit that this is mostly a bandaid, but if the flakiness is due to forces outside our control, then I think this is the best solution
> testing new configuration options

- test/axes/numericAxisTests.ts
Completely reworked to adhere to current guidelines (using `.size()` instead of `[0].length`).  Also making use of `it`s inside of `forEach`'s to test against multiple orientations easily.
Test screenshot:
> [NumericAxis Tests] - rework

- test/plots/plotTests.ts
Test screenshot:
`Plot` is incredibly odd in that it cannot render on its own.  Thus, situations that directly deal with a rendered product are not tested.  However, other cases regarding anchoring, dataset mangement, etc have been reworked to follow the new guidellines.
Part of #2630
> [PlotTests] - Rework

- plottable.js
- src/plots/plot.ts
- test/plots/piePlotTests.ts
- test/plots/rectanglePlotTests.ts
- test/plots/scatterPlotTests.ts
- test/plots/segmentPlotTests.ts
line & bar have own implementations and shouldn't be affected
line http://jsfiddle.net/6kjx5810/3/
area http://jsfiddle.net/6kjx5810/5/
bar http://jsfiddle.net/6kjx5810/4/
pie http://jsfiddle.net/6kjx5810/6/
rectangle http://jsfiddle.net/6kjx5810/2/
segment http://jsfiddle.net/6kjx5810/1/
scatter http://jsfiddle.net/6kjx5810/
Nan, Infinity, clicking outside svg bounds http://jsfiddle.net/6kjx5810/7/
> entity nearest returns undefined instead of breaking, when no data in view

- test/components/dragBoxLayerTests.ts
part of #2623
second pass; mostly `let` to `const` change
> dragBoxLayer test refactor

- test/components/guideLineLayerTests.ts
part of #2623 
second pass
`let` -> `const`
refactor tests for vertical/horizontal rendering
> guideLineLayerTests refactor

- test/components/xDragBoxLayerTests.ts
part of #2623 
second pass; mostly `let` to `const`
add a test for setting `yExtent`
> XDragBoxLayerTests refactor

- test/components/yDragBoxLayerTests.ts
part of #2623 
second pass; mostly let to const
add a test for setting xExtent
> refactor YDragBoxLayer test

- test/components/dragLineLayerTests.ts
restructure tests 
use `const` when possible
refactor vertical and horizontal tests
part of #2623
> refactor DragLineLayerTests

- test/components/selectionBoxLayerTests.ts
remove `Interactive Components ` layer
`let` -> `const`
grouping xScale tests and yScale tests
minor clean up
part of #2623
> refactor selectionBoxLayerTests

- test/dispatchers/dispatcherTests.ts
A more thorough cleaning (removing `<any>`s, etc) probably depends on https://github.com/palantir/plottable/issues/2968.
Last checkbox of https://github.com/palantir/plottable/issues/2628, at least until #2968 gets done.
> [Dispatcher tests] Clean up parent-level Dispatcher tests.

- test/components/labelTests.ts
- test/drawers/arcDrawerTests.ts
- test/drawers/arcOutlineDrawerTests.ts
- test/drawers/areaDrawerTests.ts
- test/drawers/lineDrawerTests.ts
- test/testReference.ts
Added tests for `Drawer` subclasses. Most of them only define an element name and class name, which is tested [in the superclass tests](https://github.com/palantir/plottable/pull/2976).
Part of #2622.
> [Testing Audit] Added tests for Drawer subclasses.

- test/plots/clusteredBarPlotTests.ts
close #2637 
- grouping horizontal and vertical tests into describe block
- refactor out common code to loop through orientations
> refactor clusteredBarPlotTests

- test/animators/easingAnimatorTests.ts
- test/animators/nullAnimatorTests.ts
- test/testReference.ts
Here's the new test battery:
Changes:
* `Animators.Null` actually has tests now
* `Animators.Easing` had its tests broken out to test the effects of step count, `startDelay()`, `stepDelay()`, and `stepDuration()` independently.
Should finish off #2622.
> [Testing Audit] Animators

- test/interactions/pointerInteractionTests.ts
#2628 
- loop through mouse event and pointer event
- use const when possible
> refactor pointerInteractionTests

- test/dispatchers/touchDispatcherTests.ts
closes #2789
- factor out common code in each test
- remove skipped test as that's not needed: touch event should be called inside and outside of the component for `pointerEnter` and `pointerExit` interactions to work
> clean up touchDispatcherTests

- test/interactions/keyInteractionTests.ts
- loop through key events
- use const when possible
closes #2759
> refactor keyInteractionTests

- plottable.d.ts
- plottable.js
- src/dispatchers/dispatcher.ts
- src/dispatchers/keyDispatcher.ts
- src/dispatchers/mouseDispatcher.ts
- src/dispatchers/touchDispatcher.ts
- test/dispatchers/dispatcherTests.ts
- test/dispatchers/touchDispatcherTests.ts
Refactored how `Dispatcher` registers events. Previously it used these methods:
```Typescript
// OLD DESIGN
protected _setCallback(callbackSet: Utils.CallbackSet<Function>, callback: Function): void;
protected _unsetCallback(callbackSet: Utils.CallbackSet<Function>, callback: Function): void;
```
This seemed kind of odd, since there was a method that modified non-instance fields, and subclasses had to define a new `CallbackSet` for each type of event they wanted to add listeners for, and then call `.callCallbacks()` manually. This seemed silly.
The refactored version:
```Typescript
// NEW DESIGN
protected _addCallbackForEvent(eventName: string, callback: Function): void;
protected _removeCallbackForEvent(eventName: string, callback: Function): void;
protected …
```
> [Dispatchers] Refactor architecture for clarity

- plottable.d.ts
- plottable.js
- src/components/component.ts
- test/components/componentTests.ts
As referenced in https://github.com/palantir/plottable/pull/2984.
The top-level `Component` now adds an `opacity: 0` `<rect>` to the `<svg>` before anchoring, and removes it when detaching.
On **`develop`**: https://jsfiddle.net/j6c01b1e/
On **`develop-2.0`**: https://jsfiddle.net/xwpvdrns/
On **`safariEvents`**: https://jsfiddle.net/zs8tuctx/
Repro with all three event types:
* On **`develop`**: https://jsfiddle.net/324pawue/
* On **`develop-2.0`**: https://jsfiddle.net/5fhzscr9/
* On **`safariEvents`**: https://jsfiddle.net/yen85gLp/
> Add backing <rect> to catch events on Safari.

- plottable.d.ts
- plottable.js
- src/axes/axis.ts
- src/axes/numericAxis.ts
- src/axes/timeAxis.ts
`_computedHeight` and `_computedWidth` are calculated every time; these are unnecessary cached variables
> remove unused cached variables

- plottable.d.ts
- plottable.js
- src/plots/stackedAreaPlot.ts
Cropped rendering on `StackedArea` is currently broken (as per #3032), so disabling it by default for now until the algorithm can be fixed.
> [StackedArea Plot] Default to no cropping by default
